### ISSUE TITLE
Near You tab has odd ordering

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1021]
What is the ordering logic here?

![near](https://cloud.githubusercontent.com/assets/2797729/20501700/a1fd7456-b043-11e6-98b6-27730dbff9ea.png)

A few days ago it was `SORT BY distance, time` but now it looks quite strange. And I'm not sure if that rule is the best one. For example, if there are two bus stops A and B, and their distance is 100 meters, why all the departures form A becomes first and only after that departures from B?

**Comment by rrudd** [comment]
Thanks for pointing this out. The sorting of departures from the same stop by time broke when we changed how the nearby departures are fetched from OTP. This is in the backlog as [DT-1644](https://digitransit.atlassian.net/browse/DT-1664) and will be fixed eventually.

**Comment by ttsirkia** [comment]
Seems to be fixed.
