### ISSUE TITLE
Back button UI issue with mobile devices

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1057]
In mobile devices clicking "Near you" tab opens a fullscreen view which can be closed by pressing the close button in the corner. However, I would expect that pressing mobile phone's physical back buttons does the same but this is not the case.

For example, if I have pinned Reittiopas to the start view as a shortcut, the browser will close itself when pressing back in this case because the undo stack is empty. Assuming here that I opened the "Near you" tab instantly after starting the "app".

The physical back button should always close any opened fullscreen views.

**Comment by rrudd** [comment]
Hi! This issue will be fixed as part of a larger overhaul of the navigation logic. It's currently in our backlog as [DT-1608](https://digitransit.atlassian.net/browse/DT-1608).

**Comment by vesameskanen** [comment]
This issue is no longer valid in the new layout.
