### ISSUE TITLE
Improved front page - Search

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#108]
Search related changes to new front page.

First, look through terms, and states for Position and location:
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Terms.md
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Position.md
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Location.md

Then, implement search as specified in component tests
https://github.com/HSLdevcom/digitransit-ui/tree/master/acceptance-tests/component/search

**Comment by hannesj** [comment]
Part of #130

**Comment by samuliheljo** [comment]
Part of #130
