### ISSUE TITLE
Use predefined location instead of GPS

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1135]
If the computer is connected to LAN, the estimated (IP address based) location may be kilometers away from the actual position. Therefore, there should be an option to save a location for the default starting point.

**Comment by tuukka** [comment]
This would be nice indeed. Meanwhile, you can decline geolocation and save the location as a favourite to have access to it with one click.

**Comment by ttsirkia** [comment]
Yes, this is definitely easier with the current start screen.

**Comment by tuukka** [comment]
This might be implemented without new UI by taking the location accuracy into account: if the location is at a favourite place within accuracy, use the (closest) favourite location instead.

**Comment by ttsirkia** [comment]
I don't believe that would work. For example, my location is in Leppävaara based on the IP address although living in Tapiola. If I had Sello in my favorites, my default destination would always be incorrectly there.

**Comment by ttsirkia** [comment]
Not relevant anymore.
