### ISSUE TITLE
Usability: Click on map opens "bubble"

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#122]
It seems that IOS devices are handling map popup pretty well but icons on map are harder to click at least on samsung android phones. We need two improvements:

- It should be easier to get bubble to open (I don't know if we have any other ways of doing this than to make clickable radius bigger)
- Bubble should be opened from the center of the icon, not where user clicked

**Comment by hannesj** [comment]
To get it opened from the center, we need to move from CircleMarker to Marker, with a custom icon.

**Comment by hannesj** [comment]
Part of #105

**Comment by hukka** [comment]
Waiting for #141
