### ISSUE TITLE
Dropdown caret is not clickable

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1224]
It is not possible to click the caret:

![hsl-dropdown](https://cloud.githubusercontent.com/assets/2797729/21958366/7f748496-dab5-11e6-9952-53e44ef1f35c.png)

And hovering mouse over the date or time does not show the hand cursor indicating that it is clickable.

**Comment by ttsirkia** [comment]
Caret seems to be clickable now although pointer cursor still not present although #1225 exists.

**Comment by hannesj** [comment]
Fixed by https://github.com/HSLdevcom/digitransit-ui/pull/1330
