### ISSUE TITLE
[regression] not possible to use the search bar to set a destination anymore

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#1270]
Since Friday 27th January commits, it is not possible to click on the search bar to set a destination anymore. Tested on both LG G4 and latest Firefox on both Windows 10 and Ubuntu 16.10.

**Comment by kalon33** [comment]
@samuliheljo @hannesj Did you experienced that too?

**Comment by kalon33** [comment]
I just tested with latest commits, but still, search bar is not clickable, except if I reload the page and click on it very fast during reload. It is a bit like if something transparent masked it, making it unreachable.

**Comment by kalon33** [comment]
@hannesj Do you have any idea of what could trigger this bug?

**Comment by tuukka** [comment]
@kalon33 Can you reproduce this at https://beta.reittiopas.fi/ ?

**Comment by kalon33** [comment]
@tuukka No, and maybe is this because I use default theme instead of reittiopas one (my instance is at https://transit.acolytesanonymes.org )? Is there a way to specifically test this? Because the only difference I have with upstream is my config file, that uses default theme. 

When I click on the search bar, the URL changes to /lahellasi but nothing else happens. 


----- Mail original -----

De: "Tuukka Hastrup" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 9 Février 2017 14:29:51 
Objet: Re: [HSLdevcom/digitransit-ui] [regression] not possible to use the search bar to set a destination anymore (#1270) 



@kalon33 Can you reproduce this at https://beta.reittiopas.fi/ ?

**Comment by tuukka** [comment]
@kalon33 In that case, can you reproduce at https://beta.matka.fi/ ? This is where we run the default theme in production.

**Comment by kalon33** [comment]
@tuukka: No I can't. And I see that stops are visible on the map there where they disappeared on my side (I was only able to see bike stops before I disabled it, routing is still functional though). Is this latest upstream? 

I will make a full diff between my installation and upstream this evening, and post it there. 

On OTP side, I'm nearly identical to hsldevcom/opentripplanner master: 
https://github.com/HSLdevcom/OpenTripPlanner/compare/master...kalon33:1.x.x_hsl_enhanced_paris 


----- Mail original -----

De: "Tuukka Hastrup" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 9 Février 2017 15:15:34 
Objet: Re: [HSLdevcom/digitransit-ui] [regression] not possible to use the search bar to set a destination anymore (#1270) 



@kalon33 In that case, can you reproduce at https://beta.matka.fi/ ? This is where we run the default theme in production.

**Comment by kalon33** [comment]
@tuukka Here is the difference between my Digitransit instance and upstream: 

https://github.com/HSLdevcom/digitransit-ui/compare/master...kalon33:digitransit-ui-paris?expand=1 

Do you see anything that would explain the bug that occurs? 

Thanks for your help. 

----- Original Message -----

**Comment by samuliheljo** [comment]
This happens when config has useVectorTiles: false

Then UI breaks here: https://github.com/HSLdevcom/digitransit-ui/blob/5e09823e67e3550bcfd4fbb071a3c20027d8c57f/app/component/map/non-tile-layer/StopMarkerLayer.js#L59

I have created issue to our Jira: https://digitransit.atlassian.net/browse/DT-1838

I think you have two options :
a) Wait until fix will arrive
b) submit a pull request

**Comment by kalon33** [comment]
@samuliheljo thanks for finding the origin of the bug. It's pretty new, StopMarkerLayer.js has changed its way to deal with that recently?

I unfortunately don't have the skills to fix that, so I will wait for a fix. Any possible workaround until then?

Thanks again!

**Comment by kalon33** [comment]
@hannesj any chance to get this fix before official release as this is now DT-1838?

**Comment by hannesj** [comment]
Fixed by #1331

**Comment by kalon33** [comment]
@hannesj I just merged your PR and tried it, but unfortunately, I still can't write in search bar (when I click it it doesn't select it) and stops still don't appear on the map as before.

**Comment by hannesj** [comment]
Could you check now, there was an error if config.preferredAgency was not defined.

**Comment by kalon33** [comment]
@hannesj Thanks a lot, that fixed my problem! My last remaining bug is #908
