### ISSUE TITLE
Box for arrival/departure time is too small on Firefox

### ISSUE THREAD

**Issue by harriv** [HSLdevcom/digitransit-ui#1302]
Box for arrival/departure time is too small on Firefox 51 (Win7):

![kuva](https://cloud.githubusercontent.com/assets/2283563/22620894/710dfe72-eb1e-11e6-9e49-ab6b02cc2c24.png)

Chrome displays it ok.

**Comment by ttsirkia** [comment]
I can't reproduce this with my FF51.

**Comment by harriv** [comment]
Can't reproduce either, although I saw this twice..

**Comment by hannesj** [comment]
Sorry for a late reply. This was fixed in #1230
