### ISSUE TITLE
Time picker component does not work

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1307]
Time picker component does not work at all with Firefox or Chrome. Nothing happens when the time box is clicked.

**Comment by ttsirkia** [comment]
@hannesj this is pretty critical bug, any possibilities to get this fixed before the official launch?

**Comment by ttsirkia** [comment]
Probably caused by f29798d39d657d333b23530e8554b701bd1a1098

**Comment by hannesj** [comment]
I can't reproduce this either on Chrome or Firefox. On Chrome, the native time picker is activated and you can either input the numbers with the keyboard or use the arrow keys to scroll minutes/hours. On Firefox a normal input with some validation is used. 

This change was done in https://github.com/HSLdevcom/digitransit-ui/pull/1246 and is based in task [DT-1701](https://digitransit.atlassian.net/browse/DT-1701)

**Comment by ttsirkia** [comment]
OK, so it is intended that with Firefox it is just an ordinary input field without the previous Material UI time picker component? It is kind of odd that when you click the time field, all the text gets selected and it is very bad user design that the text cursor does not blink and it does not look like an editable field. Nothing suggests that you can type new time.
![fftime](https://cloud.githubusercontent.com/assets/2797729/22853321/0f844f38-f05c-11e6-8bd6-12370db1adc8.png)


In Chrome, the caret is visible but nothing happens. Also, it is very unintuitive to start typing because nothing visually indicates that it is possible.
![caret](https://cloud.githubusercontent.com/assets/2797729/22853303/ba578480-f05b-11e6-8a66-66a04d857d7a.png)

The user experience is much worse than before.

**Comment by ttsirkia** [comment]
And, because it is `type="text"` in Firefox, you can type anything there.

**Comment by ttsirkia** [comment]
My first idea was that the previous time picker component is somehow broken, I couldn't even imagine that this was done on purpose. This is a huge drawback at least visually.

**Comment by hannesj** [comment]
The Chrome behaviour has not been changed, we have always used the native `<input type=time/>` if supported by the browser. If you feel that the Chrome implementation is not suitable, you might want to take it up with their developers. Also Firefox is planning to ship a similar native input in [Firefox 52](https://wiki.mozilla.org/TPE_DOM/Date_time_input_types).

Some of the reasons for the change:
 - User feedback, in which users explained that they are used to editing time fields with keyboard on desktop browsers
 - Material-ui timepicker was broken on Mobile IE with small viewports
 - Material-ui timepicker did not meet accessibility requirements

If you feel that you want to discuss this in more detail, I suggest you to talk to [our product owner](mailto:jari.honkonen@hsl.fi) who is the suitable person.

**Comment by ttsirkia** [comment]
Closing the ticket seems to be a perfect way of getting rid of this kind of usability issues. I think that showing the incorrect caret in Chrome, for example, is part of your technical design and has nothing to do with Google.

In Firefox, changing the background color to white and text to black would have dramatically improved the UI because then the input field would match with all other editable fields and have consistent appearance.

It seems that feedback and pull requests are not very welcome in this project so better to be just a customer and use the product as is.

I hope you get enough feedback when the service in production use and fix the usability issues then.

**Comment by tuukka** [comment]
@ttsirkia Your original report was about the time picker component not working at all, which was not the actual case. Hannes explained our reasoning and suggested contacting our concept owner. Feedback and pull requests are very welcome, but you have to realise in a big project like this, the developers can't change the concept or the priorities agreed upon. As you work at FTA, you should probably discuss this with the Matka.fi project manager there.

We're busy right now with the release in four days. Thanks to your concrete bug fix suggestions in your latest comment, there's now work in progress to further improve the time picker. If you prefer, you can re-title and reopen.

**Comment by ttsirkia** [comment]
I must comment that I do not present FTA here and writing and commenting as a customer and hobbyist.

**Comment by tuukka** [comment]
@ttsirkia I realised that but it could be interesting for you to get insider insight to how this project is managed and whether there's connections to your  day job.

**Comment by ttsirkia** [comment]
Better UI in #1335
