### ISSUE TITLE
Tabs have unintuitive colors

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1308]
When looking at this picture, I bet most of people would say that Favorites tab is selected although it is not.

![tabs](https://cloud.githubusercontent.com/assets/2797729/22665521/b1d9b95a-ecbd-11e6-977c-dcf56d6bb7d4.png)

The selected tab should have lighter background and the not selected tabs darker.

**Comment by tuukka** [comment]
This will be fixed by adding a third tab ;-) Also, the tabs will be moved above their content to make a visual connection.

**Comment by vesameskanen** [comment]
UI now works as suggested.
