### ISSUE TITLE
Map jumps back to original position persistently if bus stop popup is open

### ISSUE THREAD

**Issue by esuomi** [HSLdevcom/digitransit-ui#1360]
1. Make sure location services detect where you are.
 1. Open bus stop info popup, preferably one already in screen, probably the nearest one to you.
 1. Take the bus downtown :-)
 1. Restore app from background to check the time table for closest stop again, try to scroll a bit and the map jumps back to the previous spot. Clicking location icon jumps the map back to where you are, but any interactions stubbornly push the map view back to original location again as long as the bus stop popup is open/active.

**Comment by vesameskanen** [comment]
Popup autoPan feature disabled.
