### ISSUE TITLE
Snap CI is shutting down

### ISSUE THREAD

**Issue by esuomi** [HSLdevcom/digitransit-ui#1363]
>We have some sad news to share. Today we are announcing the end of life (EOL) for Snap CI. The planned final day will be August 1st 2017.
[ -- _Snap CI blog: Snap is Going Away_](https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/)

Better move now when things still work than letting everything catastrophically fail and then make a really stressful hustle. [Travis CI](https://travis-ci.org/), mayhaps?

**Comment by siren** [comment]
migrated to travis: https://travis-ci.org/HSLdevcom/digitransit-ui
