### ISSUE TITLE
missing svg-sprite files

### ISSUE THREAD

**Issue by Eightyplus** [HSLdevcom/digitransit-ui#1372]
New configurations added but sprite files are missing, 

```Shell
ERROR in multi ./static/svg-sprite.hameenlinna.svg
Module not found: Error: Can't resolve './static/svg-sprite.hameenlinna.svg
....
ERROR in multi ./static/svg-sprite.joensuu.svg
ERROR in multi ./static/svg-sprite.kuopio.svg
ERROR in multi ./static/svg-sprite.lappeenranta.svg
ERROR in multi ./static/svg-sprite.matka.svg
ERROR in multi ./static/svg-sprite.oulu.svg
ERROR in multi ./static/svg-sprite.turku.svg
```

**Comment by hannesj** [comment]
This should be handled by https://github.com/HSLdevcom/digitransit-ui/blob/master/webpack.config.js#L300-L314

**Comment by Eightyplus** [comment]
I been looking for this error, but now it is obvious. I only have one CONFIG and I don't need your setup.
So when all configurations are iterated e.g. hameenlinna, it will read `config.hameenlinna.js`
and CONFIG for hameenlinna is defined as such `const CONFIG = process.env.CONFIG || 'hameenlinna';`

Now when the sprite is read, `spriteMap['hameenlinna']` does not exists, only `spriteMap['rutebanken']` thus it tries to read it from the path.

I understand the change from static to dynamic mapping, which eases hosting on your behalf. But it break when a specific setup is wanted...

**Comment by vesameskanen** [comment]
Will be fixed by https://github.com/HSLdevcom/digitransit-ui/pull/1358 ( webpack skips non-configured themes).

**Comment by vesameskanen** [comment]
Recent build improvements fix this problem.
