### ISSUE TITLE
Focus outline on search input and other .noborder buttons

### ISSUE THREAD

**Issue by maciej-gurban** [HSLdevcom/digitransit-ui#1392]
Here's how it looks when you click on the main search input. Visible only until destination modal opens.

<img width="736" alt="screen shot 2017-02-26 at 19 12 50" src="https://cloud.githubusercontent.com/assets/3663640/23341826/99a209b0-fc57-11e6-9a16-153509c9a249.png">

It could be solved by either setting `outline: 0` on `.search-button`, or perhaps even better, on `.noborder` unless you really do want to keep the default browser outline on all your focusable elements and buttons.

I couldn't find any section in your README about your expectations for PRs, so I witheld from proposing a fix. Perhaps you could update it or mention it here?

**Comment by vesameskanen** [comment]
Search component replaced with a new one.
