### ISSUE TITLE
UI-layout is broken in Safari 8.0, iOS 8.0.2 iPhone 4GS

### ISSUE THREAD

**Issue by TeemuKoivisto** [HSLdevcom/digitransit-ui#1398]
Hey, so great stuff with the new app.

Only problem is that using it with legacy phones like iPhone 4GS, which iOS I haven't updated in the fear of it getting even more slower, is that the map is broken and all the UI components are mushed in together in one big blob.

I do not know in full detail why but alas my phone sucks and I rather just continue using the old one. So maybe could you add "Your browser version is not supported" - screen with a single button redirect to the old app. For me it was no problem getting back to old one but maybe some less tech-savvy people see only the broken app and can't figure out how to slide the menu screen (for which there is no indication of its existence from the main view, I think I accidentally swiped right from the edge and got it open)

Anyway that was just a minor thing that I wanted to mention, cool stack with the technologies! 😃

**Comment by Permik** [comment]
This seems to be fixed nowadays, it shows a banner that the browser is not supported anymore if you connect with an iPhone 4.
