### ISSUE TITLE
Time selector pushes "Tarkenna"-button off screen in portrait view on Firefox for Android

### ISSUE THREAD

**Issue by mestaritonttu** [HSLdevcom/digitransit-ui#1457]
When showing the route suggestions in portrait view, the time selector input expands to an unusual width and cruelly pushes the "Tarkenna"-button out of sight. This is on Firefox for Android v. 51.0.3 and 52. Device is Oneplus 3T.

Could not reproduce with desktop Firefox's responsive design view..

**Comment by hannesj** [comment]
This should have been fixed in https://github.com/HSLdevcom/digitransit-ui/pull/1415. Could you check if you can reproduce this on https://dev.reittiopas.fi/?

**Comment by mestaritonttu** [comment]
Confirmed fix on dev! Thanks :)
