### ISSUE TITLE
Support for deep linking into directions to a destination without knowing origin

### ISSUE THREAD

**Issue by EreMaijala** [HSLdevcom/digitransit-ui#1463]
With the classic, no longer available, matka.fi service, it was possible to use a link such as http://www.matka.fi/fi/?keya=&keyb=street,%20city, but this seems to be no longer possible. It would be very useful for us to be able to link to the UI with a link containing the destination address. We used it to link to directions to libraries, but I think this would be useful for others too for providing directions to e.g. store locations.

**Comment by hannesj** [comment]
Hi, this should have been fixed by https://github.com/HSLdevcom/digitransit-ui/pull/1413. Can you try if it fits your needs on https://dev.reittiopas.fi eg. https://dev.reittiopas.fi/?to=Pasilan%20kirjasto

**Comment by EreMaijala** [comment]
Hi, thanks, that should indeed do it. Will it be available also in opas.matka.fi (and when?)? I'm asking because it seems that with #1413 those parameters are only processed if config.redirectReittiopasParams is true.

**Comment by hannesj** [comment]
Added https://github.com/HSLdevcom/digitransit-ui/pull/1466 for that. The production version will be updated tomorrow according to our weekly scheme.

**Comment by tuukka** [comment]
Please re-open if there are still issues.

**Comment by EreMaijala** [comment]
This has broken recently. Both opas.matka.fi and www.reittiopas.fi just return an internal server error. Example: https://www.reittiopas.fi/?from=Kaikukatu%204,%20Helsinki&to=Mannerheimintie%201,%20Helsinki

**Comment by hannesj** [comment]
@EreMaijala Sorry, we released an buggy version during the afternoon today. It has now been fixed and a test added for this feature.

**Comment by EreMaijala** [comment]
@hannesj It's broken again..
