### ISSUE TITLE
Missing translations in settings

### ISSUE THREAD

**Issue by hugovk** [HSLdevcom/digitransit-ui#1489]
In the settings, "Ei lippuvyöhykerajoitusta", "Ei rajoitusta" and "Liikun pyörätuolilla" are hardcoded in Finnish and not translated on the English and Swedish pages:

![EN](https://cloud.githubusercontent.com/assets/1324225/24134507/7ca8a428-0e0d-11e7-8017-6f532949c927.png)

![SV](https://cloud.githubusercontent.com/assets/1324225/24134549/c8f3f68e-0e0d-11e7-80eb-bd6c129c8dd8.png)

The translations used in the classic site for the first one are "No fare zone restrictions" and "Ingen biljettzonbegränsning". (The others don't seem to be in the classic site.)

The hardcoded Finnish strings are in [config.default.js](https://github.com/HSLdevcom/digitransit-ui/blob/69564591ec5b566c3d303b3925b7dea481e56d9f/app/configurations/config.default.js#L299-L310).

**Comment by vesameskanen** [comment]
https://digitransit.atlassian.net/browse/DT-2473

**Comment by vesameskanen** [comment]
Fixed by https://github.com/HSLdevcom/digitransit-ui/pull/2188
