### ISSUE TITLE
Errors when npm install

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#149]
Hi, I got the following errors when npm install:

nicolas@darwin:~/packaging/sources/digitransit-ui$ npm install
npm ERR! git rev-list -n1 2.0: fatal: ambiguous argument '2.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 2.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 2.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 2.0: 
npm ERR! git rev-list -n1 2.0: fatal: ambiguous argument '2.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 2.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 2.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 2.0: 
npm ERR! git rev-list -n1 2.0: fatal: ambiguous argument '2.0': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 2.0: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 2.0: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 2.0: 
npm ERR! Linux 4.2.0-10-generic
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.25
npm ERR! npm  v3.3.3
npm ERR! code 128

npm ERR! Command failed: fatal: ambiguous argument '2.0': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nicolas/packaging/sources/digitransit-ui/npm-debug.log

**Comment by tuukka** [comment]
`npm install` seems to have issues too often nowadays :-( Did you try with a clean checkout of `digitransit-ui` and without old `node_modules` and/or `~/.npm`? The error message probably means that npm is trying to install the git version of some package tagged as "2.0", but there is no such version (anymore?). `npm-debug.log` might contain a hint about which package is causing this.

**Comment by hukka** [comment]
It seems you are using a pretty old version of node (from Jan 2014), while we are deploying with 0.12 and likely soon with 4.1. Also testing with a short Dockerfile works for me:

    FROM node:0.12
    MAINTAINER Reittiopas version: 0.1
    
    RUN apt-get update
    RUN apt-get install -y git libglew-dev
    
    RUN npm install -g npm@3
    
    # Get initial (cacheable) code
    RUN mkdir -p digitransit-ui && \
      cd digitransit-ui && \
      git clone https://github.com/HSLdevcom/digitransit-ui . && \
      npm install && \
      npm run static && \
      npm run build

Does upgrading node resolve the issue for you?

**Comment by kalon33** [comment]
Unfortunately not. I tried with latest npm 3.3.5 (obtained from running sudo npm install -g npm) and latest nodejs 4.1.2 compiled from source, without success (same git related errors)

**Comment by Macroz** [comment]
Yesterday, starting from clean node_modules and compiling node v0.12.7 from source, using npm 3.3.5 from PPA, all worked eventually, but only after a bunch of retries.

**Comment by samuliheljo** [comment]
I'm closing this. these instructions should work:
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Installation.md
