### ISSUE TITLE
npm install fails when making a pull request

### ISSUE THREAD

**Issue by AlexLoyko** [HSLdevcom/digitransit-ui#1526]
My pull request stopped passing npm install for some reason(works well locally).
Looks like the old version of node (.10.*)

Pull request #1513.

Here is the log:
 $ npm install
npm WARN deprecated mapbox-gl-function@2.1.0: This package has been merged with the 'mapbox-gl-style-spec' package
npm ERR! not a package /tmp/npm-6482-MZNC6jJr/github.com/HSLdevcom/gemini-browserstack
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'mapbox/sphericalmercator' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'digitransit-ui'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.13.0-105-generic
npm ERR! command "/opt/local/nvm/v0.10.37/bin/node" "/opt/local/nvm/v0.10.37/bin/npm" "install"
npm ERR! cwd /var/snap-ci/repo
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/snap-ci/repo/npm-debug.log
npm ERR! not ok code 0
Command npm install failed with status 1.

Any advice?

**Comment by siren** [comment]
I think this is obsolete now
