### ISSUE TITLE
Missing BS_USERNAME and BS_ACCESS_KEY at the gemini testing stage

### ISSUE THREAD

**Issue by AlexLoyko** [HSLdevcom/digitransit-ui#1527]
When I pushed the latest commit on the #1513, it fails the stage 4 test because of this error:

Error: Missing BrowserStack credentials. Did you forget to set BS_USERNAME and/or BS_ACCESS_KEY?
    at Error (native)

Can anybody help me figure out where those two get set?

Thanks!

**Comment by tuukka** [comment]
They are set as environment variables that are configured in the admin interface of Snap CI. Further, they are configured as "secure" which means that they are not available in pull requests outside the HSLdevcom organisation. I'm not sure if that restriction is necessary. In any case, you should be able to run the tests locally using your own BrowserStack account.

**Comment by AlexLoyko** [comment]
Okay I see.

Thanks!
