### ISSUE TITLE
Un-translated text on RouteMarkerPopup component

### ISSUE THREAD

**Issue by laidig** [HSLdevcom/digitransit-ui#1555]
There are two Finnish button texts on RouteMarkerPopup:
[Lähdön tiedot and Linjan tiedot](https://github.com/HSLdevcom/digitransit-ui/blob/b37d4dc72786d853a8d3764e588ed25f2aa2bdac/app/component/map/route/RouteMarkerPopup.js#L72)

If you let me know what an appropriate English translation of this is, I'll submit a PR.

**Comment by tuukka** [comment]
Good catch! "Lähdön tiedot" means "Trip information" or "View trip", and "Linjat tiedot" means "Route information" or "View route".
