### ISSUE TITLE
Changing date on timetable view resets always to today

### ISSUE THREAD

**Issue by harriv** [HSLdevcom/digitransit-ui#1562]
https://www.reittiopas.fi/linjat/HSL:2110/aikataulu/HSL:2110:0:01

When trying to change the date to "tomorrow", screen flashes and date resets to "today".

Looks like I can select only week days, but weekends and holidays (1.5. and 25.5.) cannot be selected.

I'm using Firefox 53.0 on Linux.

**Comment by vesameskanen** [comment]
Seems to be fixed in later releases. Could you recheck and close the issue if the day selector works fine?

**Comment by harriv** [comment]
Seems to work.
