### ISSUE TITLE
search parameters change departure to arrival when requesting previous routes

### ISSUE THREAD

**Issue by ebalink** [HSLdevcom/digitransit-ui#1566]
(This is unfortunately not so formal description of a bug (or a problematic feature) as this is only based on my own experiences as a user of the service and I haven't looked in to the code.)

Use case: user is trying to find route from location A to location B based on the time when they are free to departure. User chooses the search conditions as "leaving", "today" and the time of estimated departure. Then they receive a few results (in mobile just 3) and see that they won't be able to make to the location B in the required time so they will obviously have to advance their departure. The user chooses option "Earlier" from the bottom of the page. ...but now the search conditions change option "leaving" to "arriving" and the user does not see the route options for leaving e.g. 5 or 10 minutes earlier but routes that arrive earlier which can be confusing and makes difficult to browse back to the original suggested route.

This also happens if the user first chooses "later" to see later routes and then tries to return back to previous seen routes choosing "earlier". It's also difficult for user to notice the change in the search options.

**Comment by siren** [comment]
duplicate? https://github.com/HSLdevcom/digitransit-ui/issues/1354

**Comment by CryptidVulpes** [comment]
@siren, The description looks similar to the issue I created, yes.

**Comment by hannesj** [comment]
This should be fixed with https://github.com/HSLdevcom/digitransit-ui/pull/1639, which is already deployed in production
