### ISSUE TITLE
Location retrieval not supported on Chrome 58?

### ISSUE THREAD

**Issue by Ozzee** [HSLdevcom/digitransit-ui#1569]
The page says location retrieval not supported on Chrome 58.0.3029.81 (64-bit) macOS.

Screenshot attached to illustrate with the settings showing location is allowed.
<img width="839" alt="screenshot 2017-05-04 10 40 37" src="https://cloud.githubusercontent.com/assets/917061/25694308/b4756b22-30b6-11e7-8878-25fe43d73077.png">

**Comment by tuukka** [comment]
What's the address of the page? https://www.reittiopas.fi works for me on Chrome 58.0.3029.96 (64 bit) on Windows 10.

**Comment by rrudd** [comment]
Could not reproduce either with the exact same setup as @Ozzee
