### ISSUE TITLE
Show disruptions in itinerary details when one of used routes is involved

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#1573]
It would be great to have a message or an indicator next to the line number and icon to indicate that the line you will possibly traveling on is involved in a disruption, in itinerary details and/or summary.

**Comment by vesameskanen** [comment]
The summary now shows the  disruption mark (red triangle) on disrupted routes.

**Comment by kalon33** [comment]
Thanks!

**Comment by kalon33** [comment]
Would it be possible to have something like a notification that can be unfolded to have details about the disruption in the itinerary? (A bit like what's done in OTP default interface, but better looking)
