### ISSUE TITLE
Walking speed unit m/min is odd

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1594]
Estimating your walking time as meters per minute is very hard because that kind of units is never used.

Most of the people know that 5 km/h is quite typical walking speed, 7 km/h requires quite fast walking and 3 km/h is rather slow. But I had to calculate that 5 km/h is 83 m/min. Didn't know that and cannot estimate any speeds using that unit.

Suggesting to change the unit.

**Comment by jolkkola** [comment]
This has now been changed. The unit will change in the production version once the cycling & walking feature has been completed and merged to the master branch.
