### ISSUE TITLE
Disruption infos are not working anymore

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#1729]
Since the switch to per feedID service-alerts, disruption info is not working anymore clicking on "!" in Digitransit homepage (tested in both local instance and https://dev.digitransit.fi).

Indeed, currently there's some service-alerts here: dev-api.digitransit.fi/realtime/service-alerts/v1/?debug 

`header { gtfs_realtime_version: "1.0" incrementality: FULL_DATASET timestamp: 1500646365 } entity { id: "57212" alert { active_period { start: 1500641480 end: 1500651000 } informed_entity { agency_id: "HSL" route_id: "1086" route_type: 3 trip { route_id: "1086" direction_id: 0 } } informed_entity { agency_id: "HSL" route_id: "1086" route_type: 3 trip { route_id: "1086" direction_id: 1 } } effect: UNKNOWN_EFFECT description_text { translation { text: "Helsingin sis\303\244isen liikenteen linja 86, my\303\266h\303\244styy. Syy: tie poikki. Paikka: Hevossalmen silta. Arvioitu kesto: 15:30 - 18:30." language: "fi" } translation { text: "Helsingfors lokaltrafik, linje 86, f\303\266rsenas. Orsak: gatan avst\303\244ngd. Plats: Hevossalmen silta. Ber\303\244knad tid: 15:30 - 18:30." language: "sv" } translation { text: "Helsinki local traffic, line 86, will be delayed. Cause: road block. Location: Hevossalmen silta. Estimated time: 15:30 - 18:30." language: "en" } } } }`

but looking at dev.digitransit.fi at the same time, we got that:

![bug](https://user-images.githubusercontent.com/460731/28467261-8fe2b114-6e2f-11e7-9654-8ad367958277.png)

Please fix

**Comment by siren** [comment]
Hi and thanks for the reporting this. it seems that we have a configuration error in dev.digitransit.fi (and opas.matka.fi).

There's a section in config where you specify the feed ids for the ui, for example here:

https://github.com/HSLdevcom/digitransit-ui/blob/master/app/configurations/config.matka.js#L35

We're currently listing only MATKA there but it should contain other gtfs feeds too, like 'HSL' for example.
