### ISSUE TITLE
Prioritize line numbers in search

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#1936]
Picture explains:
![kuva](https://user-images.githubusercontent.com/2797729/32563062-e3e2f6fe-c4b8-11e7-971b-2740652e3962.png)

If there is a string in a search box starting with digits, treat it as a line number - or at least show the matching lines on top of the results.

**Comment by ttsirkia** [comment]
This seems to work with two-digit line numbers. When there are three digits, the situation as in above occur.

**Comment by vesameskanen** [comment]
There is a task in backlog for this:  https://digitransit.atlassian.net/browse/DT-2216

**Comment by ttsirkia** [comment]
Seems to be fixed.
