### ISSUE TITLE
Purpose of the fading effect

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#2005]
What is the purpose of this fading effect:

![kuva](https://user-images.githubusercontent.com/2797729/33454035-399520b8-d620-11e7-9953-cd1b4c8edd74.png)

It makes the readibility quite poor at least in my opinion and does not look very pretty.

**Comment by hannesj** [comment]
This is fixed in https://github.com/HSLdevcom/digitransit-ui/commit/f7351318a2999e94b9b01d7a6d352219ad0a6b19#diff-64ae7cf2437953d47f21132fc71aebd2
