### ISSUE TITLE
Map bug: water has addresses

### ISSUE THREAD

**Issue by AlexLoyko** [HSLdevcom/digitransit-ui#2074]
When clicking in the middle of the water, a popup does not say a selected location, rather it shows the address that does not pertain to that point on the map at all.
<img width="550" alt="screen shot 2017-12-27 at 2 49 34 pm" src="https://user-images.githubusercontent.com/13985766/34391729-95177dfa-eb15-11e7-8357-5afc0a328e3e.png">

**Comment by vesameskanen** [comment]
Reverse geocoding picks the closest address. Apparently search radius should be significantly smaller.
Thanks for pointing  out the issue!

**Comment by AlexLoyko** [comment]
Thank you for getting back so promptly! 
That makes sense! Thank you!

**Comment by vesameskanen** [comment]
Search radius decreased to 100 m from 1 km.
