### ISSUE TITLE
Linking with 'from' and 'to' url params broken

### ISSUE THREAD

**Issue by EreMaijala** [HSLdevcom/digitransit-ui#2078]
Functionality added in #1463 is broken and parameters are either ignored or giving results. Example: 

https://www.reittiopas.fi/?from=Kaikukatu%204,%20Helsinki&to=Mannerheimintie%201,%20Helsinki

**Comment by EreMaijala** [comment]
Seems to be working in opas.matka.fi, though.

**Comment by vesameskanen** [comment]
Fixed by: https://github.com/HSLdevcom/digitransit-ui/releases/tag/20180115https://github.com/HSLdevcom/digitransit-ui/releases/tag/20180115
