### ISSUE TITLE
Old version of user interface in matka.fi?

### ISSUE THREAD

**Issue by kemkim** [HSLdevcom/digitransit-ui#2112]
I noticed, that there is difference between HSL Reittiopas and Matka.fi at least considering their user interface. HSL Reittiopas has gotten new user interface. Has their code regarding UI diverged or is the new UI of HSL Reittiopas also planned to introduced to Matka.fi?

**Comment by kemkim** [comment]
![hslreittiopas1](https://user-images.githubusercontent.com/19935824/35009397-0dddd0f2-fb08-11e7-9a0d-7e4d81e5747c.png)
![matkarp](https://user-images.githubusercontent.com/19935824/35009400-1222fa66-fb08-11e7-9355-45c747ac9111.png)

**Comment by vesameskanen** [comment]
New UI version released in opas.matka.fi 20. january 2018.
