### ISSUE TITLE
Bug in bus stop timetable screen, results not found

### ISSUE THREAD

**Issue by kemkim** [HSLdevcom/digitransit-ui#2113]
Rauma local bus stop timetable screen shows that results not found. So far I have only got this error when trying to watch Rauma local bus route timetables.

![raumabussi](https://user-images.githubusercontent.com/19935824/35009764-41ce157e-fb09-11e7-9e83-2e8052afdd31.png)

![raumabustop](https://user-images.githubusercontent.com/19935824/35009690-05dc58b4-fb09-11e7-9c9b-979bf906757e.png)

**Comment by vesameskanen** [comment]
I can  confirm the problem. 
https://digitransit.atlassian.net/browse/DT-2424

**Comment by pailakka** [comment]
Fix is deployed to production
