### ISSUE TITLE
Viewing an individual line route is broken

### ISSUE THREAD

**Issue by matiaskorhonen** [HSLdevcom/digitransit-ui#2131]
> Uncaught TypeError: Cannot read property 'routes' of undefined

<img width="554" alt="2018-01-29_10-37-53_u1x7p" src="https://user-images.githubusercontent.com/43314/35500839-7b514ab0-04e0-11e8-861f-10419f3a2716.png">

<https://www.reittiopas.fi/linjat/HSL:1008>

**Comment by pailakka** [comment]
Seems to be working currently

**Comment by matiaskorhonen** [comment]
So it does…
