### ISSUE TITLE
Choosing between departure and arrival time too complex

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#2262]
Nowadays the pane looks like this:

![kuva](https://user-images.githubusercontent.com/2797729/39415509-e37b4056-4c4c-11e8-87f3-24680c084f1e.png)

In order to define the time as arrival time, you have to click the settings and choose the option there. This very basic use case and should be available without additional clicks.

**Comment by vesameskanen** [comment]
Thanks for feedback, it definitely makes sense.

**Comment by ttsirkia** [comment]
Fixed now.
