### ISSUE TITLE
Bicycle station status symbols are confusing

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#2333]
The status icons of the bicycle stations are confusing:

![kuva](https://user-images.githubusercontent.com/2797729/41190923-e331bdba-6bef-11e8-9eaf-157d18d14ac1.png)

The tick mark in the green symbol gives an impression that the station is in operation and the cross in the red that it is not operational. The orange symbol with clock hands is the most confusing, it is a sign to wait something but what?!

Suggesting to replace the icons with a progress bar or a background color for the numbers that would be the same indication as in the map.

**Comment by vesameskanen** [comment]
Makes sense. Thanks for feedback!

**Comment by ttsirkia** [comment]
This is not relevant anymore as the visual appearance has totally changed.
