### ISSUE TITLE
Fix date formatting of day selector

### ISSUE THREAD

**Issue by datarttu** [HSLdevcom/digitransit-ui#2907]
![Date format example](https://user-images.githubusercontent.com/36631098/63534754-99b25900-c518-11e9-8bc6-c03b8980c31f.png)

Just a small detail I noticed in the Reittiopas UI: the month number should have a trailing `.` character, according to the [Finnish ortography rules](http://kielitoimistonohjepankki.fi/ohje/53). Probably this can be fixed by modifying [DateSelect.js](https://github.com/HSLdevcom/digitransit-ui/blob/543099390261dd35785e466940ed07fdd5cf56cf/app/component/DateSelect.js#L40). I am not very familiar with the app structure, though.

I also found out that changing the UI language in the top pane does not change the date format. This is problematic since the current format uses Finnish weekday abbreviations. Is there a simple way to add localization to the date formats?

**Comment by optionsome** [comment]
We can easily fix the first issue with missing trailing '.'. The other issue is slightly more complicated. We do have localized weekday abbreviations but they do not always update properly when you change the language.

**Comment by optionsome** [comment]
The fixes for the aforementioned issues are now in production.
