### ISSUE TITLE
[Route] Bus marker stays on the last stop

### ISSUE THREAD

**Issue by diogofigueiredo** [HSLdevcom/digitransit-ui#3445]
At the end of the route, the bus marker stays on the last stop. The frontend doesn't seem to receive any information to remove the marker from the map. 

![Screenshot 2020-08-07 at 10 40 31](https://user-images.githubusercontent.com/692498/89635134-70601980-d89e-11ea-99ba-c82fd2becc4f.png)

**Comment by optionsome** [comment]
Thank you for your observation. Haven't investigated this yet but I think it's possible that we could clean those vehicles from the map better. Were those vehicles already there instantly when you opened the map or did you have the view open for a while and the vehicles started piling up on the last stop?

**Comment by diogofigueiredo** [comment]
After following the bus for a while they started pilling up on the last stop.

**Comment by optionsome** [comment]
I created a ticket about this on our backlog. I think we can add a "last updated timestamp" to the vehicle markers and remove them if they have not received updates in the last 2ish minutes.

**Comment by vesameskanen** [comment]
fixed now
