### ISSUE TITLE
[next] Footer items are not rendered

### ISSUE THREAD

**Issue by leonardehrenfried** [HSLdevcom/digitransit-ui#3735]
DT 1 allowed you to show links to detail pages in the bottom left of the map:

![Screenshot from 2020-11-19 10-53-34](https://user-images.githubusercontent.com/151346/99653163-fcb2d880-2a58-11eb-8d06-7eaf1f83cece.png)

In next the `config.footer` is not rendered anymore.

Since we need this, we would like to contribute this but we are unsure how to go about this.

I can see the following places to render these links and would like to coordinate with you to increase the changes of a PR being accepted:

- top bar
- below the search boxes where there is quite a bit of whitespace
- at the old place: bottom left of the map

![Screenshot from 2020-11-19 11-21-02](https://user-images.githubusercontent.com/151346/99653597-81055b80-2a59-11eb-8cd9-67510edd51f9.png)

Do you have any plans for this and can advise which place would be most suitable?

cc @hbruch

**Comment by vesameskanen** [comment]
Hi,

Unfortunately we do not have exact plans for that yet. I expect that details like this will be designed during the next 3 months, because the plan was to get a working 'generic' DT2 instance up and running early 2021.

**Comment by leonardehrenfried** [comment]
It appears that these items are back, isn't it?

I checked out the latest version of `next` and the default configuration seems to have them.

![Screenshot from 2021-03-24 11-12-48](https://user-images.githubusercontent.com/151346/112294739-6fe08b80-8c93-11eb-9fec-4fc1685d0f0f.png)
