### ISSUE TITLE
[next] i18n context lost when clicking on autosuggest and other components

### ISSUE THREAD

**Issue by leonardehrenfried** [HSLdevcom/digitransit-ui#3837]
When using the plain digitransit frontpage, ie. when entering the origin and destination there and not jumping straight into a route search, the language context appears to use the fallback language instead of the selected one when you click on one of the address autocomplete boxes.

![Screenshot from 2021-01-04 16-30-13](https://user-images.githubusercontent.com/151346/103551245-5efd5680-4eaa-11eb-9cc0-8e942b028ac3.png)

Here is also a video of the problem: https://leonard.io/language-context-broken.webm

A while back I added the code for setting up the various language contexts: https://github.com/HSLdevcom/digitransit-ui/pull/3709

However in in https://github.com/HSLdevcom/digitransit-ui/commit/89527ea783c145f735de54058835ae1529bcbdc3 the init code was moved from the top of the file to the constructor. What was the reason for this change?

**Comment by leonardehrenfried** [comment]
Hmm, I'm trying a few combinations of initialising the i18n context but cannot find the correct one. In order to have a quicker iteration cycle I'm trying to write a test to pinpoint the problem, however I'm seeing the following error:

```
❯ yarn run digitransit-component-tests
yarn run v1.21.1
$ lerna run test --scope '@digitransit-component/*'
lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including "@digitransit-component/*"
lerna info filter [ '@digitransit-component/*' ]
lerna info Executing command in 13 packages: "yarn run test"
lerna ERR! yarn run test exited 1 in '@digitransit-component/digitransit-component-autosuggest-panel'
lerna ERR! yarn run test stdout:
$ mocha -r esm test.generated
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run test stderr:

/home/lenni/dev/herrenberg/digitransit-ui/digitransit-component/packages/digitransit-component-autosuggest-panel/src/index.js:45
    <div className={styles['itinerary-search-control']}>
    ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.

lerna ERR! yarn run test exited 1 in '@digitransit-component/digitransit-component-autosuggest-panel'
lerna WARN complete Waiting for 8 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It seems like this JSX is not compiled correctly during the test execution. Do the component tests work?

**Comment by vesameskanen** [comment]
We have noticed several bugs in i18n localization of digitransit-component packages. The errors appeared when build was updated quite radically, and the root cause is unknown. There are some quick fixes - latest one made today - which most likely fix the bugs.  The actual root cause should be discovered and fixed, too.
