### ISSUE TITLE
Current next container image does not start up

### ISSUE THREAD

**Issue by leonardehrenfried** [HSLdevcom/digitransit-ui#4155]
### Steps to reproduce
```
docker run -it --pull=always -p 8080:8080 hsldevcom/digitransit-ui:next
```
### Expected behaviour
I would expect the node process to start up and be available on port 8080.

### Actual behaviour
The process just drops into the nodejs shell. No service starts up.

Note that if you do the same with a next container from a week before, the service starts up correctly:

```
docker run -it --pull=always -p 8080:8080 hsldevcom/digitransit-ui:next-prod
```

**Comment by optionsome** [comment]
I was able to reproduce the issue. Weird thing is that in our kubernetes environment the image appears to work perfectly fine. We'll look into it but if you happen to know what could be wrong, let us know.

**Comment by leonardehrenfried** [comment]
I'm still experimenting a bit but it seems related to the environment variable $NODE_OPTS. When It's empty then the node intepreter or yarn seems to think that you want to execute a file called `""` (empty string) and drops into a console instead.

**Comment by leonardehrenfried** [comment]
Yes, `$NODE_OPTS` was indeed the problem as an empty value was confusing node/yarn.

If you set a value for it then it works.

```
docker run -it --pull=always -p 8080:8080 --name dt --rm -e NODE_OPTS="--title=digitransit-ui" hsldevcom/digitransit-ui:next
```

Presumably in your k8s cluster you set this env variable, correct?

Would you welcome a PR which sets `NODE_OPTS=--title=digitransit-ui` (or any other harmless default) in the Dockerfile?

**Comment by optionsome** [comment]
Ok thanks for figuring it out. Pull request is welcome. However, I'm not sure what caused this change. Also, I noticed the size of the docker image has grown  from ~590mb to ~705mb.

**Comment by leonardehrenfried** [comment]
I think that it was the update to yarn 2 that caused this: https://github.com/HSLdevcom/digitransit-ui/commit/0dcb6c5e74e251ffdf5fcfc15f3d9ab78102cba1

It seems that yarn 2 is handling environment variables differently and doesn't ignore them when they are empty. Not sure if this is a feature or a bug.

**Comment by leonardehrenfried** [comment]
But yeah, no idea why the image has ballooned.

**Comment by optionsome** [comment]
Found the reason for the image size change. Cache cleaning didn't remove cache under .yarn/berry/cache directory in the working directory. Fixed it here https://github.com/HSLdevcom/digitransit-ui/pull/4162
