### ISSUE TITLE
Days in route schedule view are not translated

### ISSUE THREAD

**Issue by leonardehrenfried** [HSLdevcom/digitransit-ui#4173]
## Steps to reproduce

- Visit https://reittiopas.hsl.fi/linjat/HSL:2200/aikataulu/HSL:2200:1:01?locale=en
- Switch locale to English if necessary
- See the service days are not translated and show the Finnish "ti-pe"

![Screenshot from 2021-05-19 16-44-25](https://user-images.githubusercontent.com/151346/118833188-8dac2480-b8c1-11eb-9370-02375b0f1db0.png)

**Comment by vesameskanen** [comment]
https://digitransit.atlassian.net/browse/DT-4689

**Comment by AleksiSiitari** [comment]
Fix merged to next

**Comment by leonardehrenfried** [comment]
Thanks for fixing it!
