### ISSUE TITLE
Suggestion: Add a border between the sidebar and the map

### ISSUE THREAD

**Issue by ahmed-nawar** [HSLdevcom/digitransit-ui#4252]
When the map is loading the map tiles, the map is white so the two sections merge for a couple of seconds.
Suggestion: Add a border/shadow on the right border of the sidebar.

![image](https://user-images.githubusercontent.com/84456072/121879050-b54dab80-cd0c-11eb-994b-8b2af2c2a196.png)

**Comment by vesameskanen** [comment]
Only front page has such border. I will check what the designers think.

**Comment by vesameskanen** [comment]
Will be added - https://digitransit.atlassian.net/browse/DT-4804

**Comment by AleksiSiitari** [comment]
Was added in PR #4280
