### ISSUE TITLE
Own favorites are not shown

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#4349]
When clicking the favorites, they are not shown:

![kuva](https://user-images.githubusercontent.com/2797729/131178474-b4a18c42-47c4-4943-92df-e7efddb3f26f.png)

If you click the arrow to right and then back to left, the same view is correctly populated with the favorites.

**Comment by vesameskanen** [comment]
Confirmed.

**Comment by ttsirkia** [comment]
Fixed in #4352
