### ISSUE TITLE
404 Resource not found

### ISSUE THREAD

**Issue by dancesWithCycles** [HSLdevcom/digitransit-ui#4357]
Hi folks,
Thank you so much for maintaining this repo. Appreciate! While studying the docs, I came across this [link](https://raw.githubusercontent.com/HSLdevcom/digitransit-ui/next/README.md#L34) in line 34 in the [README](https://github.com/HSLdevcom/digitransit-ui/blob/next/README.md) file. It responds with ```404 Resource not found```. I just wanted to share this observation. Cheers!

**Comment by optionsome** [comment]
I think it was the styleguide link? We removed it after this issue was created so I think this issue should be now resolved.
