### ISSUE TITLE
Return citybike station should not display available bikes count

### ISSUE THREAD

**Issue by hbruch** [HSLdevcom/digitransit-ui#4394]
In a displayed trip itinerary, for citybike legs the lending and returning citybike station are shown in the map and itinerary details, e.g. with [this trip](https://reittiopas.hsl.fi/reitti/Angervotie%2010%2C%20Helsinki%3A%3A60.21926967514075%2C24.889698028564457/Mannerheimintie%203%2C%20Helsinki%3A%3A60.16863880656824%2C24.94029521942139?arriveBy=false&locale=en&time=1632886802.506):
<img width="401" alt="grafik" src="https://user-images.githubusercontent.com/2187389/135199455-38441bb1-1f47-4ea1-8e2f-fb433cce2c08.png">

<img width="436" alt="grafik" src="https://user-images.githubusercontent.com/2187389/135199679-f557edcc-4b5e-4b92-8365-cd721041f6c7.png">

While it makes sense to display availabilty information for the lending station, this information is not necessary for the return station (we got user feedback asking if these numbers indicate some kind of ordering of trip legs).

We suggest to remove the availabilty badge from the return station.

If you are in favor of this change, we possibly might implement this.

**Comment by optionsome** [comment]
Yes I think removing the badge for the return station has been in our plans as well, but we haven't got a ticket yet for doing it and I doubt we will do it in the near future, so you can do it if you have time and create a PR.
