### ISSUE TITLE
No "Start CityBike Rental" leg shown in itinerary details

### ISSUE THREAD

**Issue by hbruch** [HSLdevcom/digitransit-ui#4400]
**Expected behavior:**
Itinerary details with citybike rental should display details for the rental's start station.

**Current behavior:**
No station information is shown:
<img width="491" alt="grafik" src="https://user-images.githubusercontent.com/2187389/136511234-c1effe70-29b9-41d4-a64a-90125556afba.png">
(Example route: https://reittiopas.hsl.fi/reitti/Bulevardi%2031%20A%2C%20Helsinki%3A%3A60.1632039064492%2C24.931411743164066/Liisankatu%2014%2C%20Helsinki%3A%3A60.17394340330982%2C24.95518684387207/0?arriveBy=false&fromMap=origin&locale=en&time=1633675611.8119)

**Comment by vesameskanen** [comment]
We already have a bug ticket https://digitransit.atlassian.net/browse/DT-4986. Will be fixed.

**Comment by optionsome** [comment]
This is now fixed with https://github.com/HSLdevcom/digitransit-ui/pull/4404 .
