### ISSUE TITLE
Digitransit-ui should indicate trip_headsign

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#451]
In itinerary details, Digitransit-ui should give vehicle trip_headsign value (which is returned by OTP from GTFS data), to be sure to take the vehicle in the proper direction. There's sometimes multiple vehicles on the same line, on the same side, having different itineraries or stop patterns.

**Comment by tuukka** [comment]
Agree. Even better, there's stop_headsign for situations where the trip headsign can change along the route.

**Comment by hannesj** [comment]
This Is covered by [DT-839](https://digitransit.atlassian.net/browse/DT-839)

**Comment by samuliheljo** [comment]
As hannesj mentioned, this is on our Jira backlog, no need to recreate anything. This is not immediate concern for us, but we'll fix it "at some point".

However, pull request are more than welcome

**Comment by kalon33** [comment]
Is there specific design guidelines to follow? Or adding in itinerary details something like " - Aéroport Charles de Gaulle" (as a headsign example) or " towards Aéroport Charles de Gaulle" to line designation (like Train B, which would give for example "Train B - Aéroport Charles de Gaulle") is enough?

I'm new to js but I can't promise I will not have a look if I have time at some point (and as missing this information in Paris is really problematic on some main transit lines as I said before).

**Comment by tuukka** [comment]
There is no concrete design for this. I would separate the headsign by a space, giving your example as "Train B Aéroport Charles de Gaulle". In my experience, the less separation between route and destination, the better.

**Comment by samuliheljo** [comment]
<img width="505" alt="screen shot 2016-04-07 at 15 48 31" src="https://cloud.githubusercontent.com/assets/1298522/14351488/43137e00-fcd8-11e5-854f-e74a724e339d.png">

Like so: "Länsiterminaali"

**Comment by kalon33** [comment]
I tried to put stoptime.pattern.headsign variable from app/component/departure/next-departures-list.cjsx into the proper line of app/component/itinerary/legs/transit-leg.cjsx (adding proper Require), but that doesn't work. Any idea of which variable I could use?

**Comment by tuukka** [comment]
@kalon33 `@props` is what the `TransitLeg` component (or any other component) gets as parameters, so no need to add any requires to get parameters. Instead, you should change the GraphQL query `ItineraryPlanContainerFragments` at `app/queries.js` to add `trip {  tripHeadsign }` under `legs`, as that determines what is available for each leg in @props. (Unfortunately, `stop_headsign` doesn't seem to be exposed by the GraphQL API.) You can read more about our GraphQL API here: http://digitransit.fi/en/developers/service-catalogue/apis/routing-api/

**Comment by kalon33** [comment]
@tuukka I made an attempt to it, but either I got bus number replaced by "undefined" or the itinerary details refused to load. My latest try is here: https://github.com/kalon33/digitransit-ui/commit/95866a1c41af6316dde2760ad77c0b1eb5b0346e

An idea?

Thanks for your help.

**Comment by kalon33** [comment]
That should be fixed with PR #494 , thanks you all for your help!

**Comment by kalon33** [comment]
you can now close https://digitransit.atlassian.net/browse/DT-839 ;)
