### ISSUE TITLE
Errors when open chat

### ISSUE THREAD

**Issue by ramialkaro** [HSLdevcom/digitransit-ui#4598]
### Errors when open chat
When open chat for the first time in the console there will be few unnecessary logs 

![error message when open chat](https://user-images.githubusercontent.com/45596102/174427797-987fe237-0b28-4417-ac2a-9907ef5e5e6a.gif)

**Comment by vesameskanen** [comment]
Thanks for feedback, I have forwarded it to the development team.

**Comment by vesameskanen** [comment]
It seems that the problem is related to the ninchat component. Hopefully its developers will fix it at some point.
