### ISSUE TITLE
Realtime timetables broken in Tampere

### ISSUE THREAD

**Issue by kristianka** [HSLdevcom/digitransit-ui#4608]
Hi!

Realtime timetables on stops have been broken for an about week now. Google Maps still shows them correctly, but no other application.

<img width="385" alt="image" src="https://user-images.githubusercontent.com/49764796/179560040-c726a25f-19da-46ec-8fdd-7c592cf3e7f2.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/49764796/179560297-611503da-174b-405b-8a1f-6f4acdd4457b.png">

**Comment by optionsome** [comment]
Thanks for pointing this out. It should be fixed now. Will have to see if it happens again.

**Comment by kristianka** [comment]
Seems to be happening again since yesterday. First img is from [reittiopas](https://reittiopas.tampere.fi/pysakit/tampere%3A0822) and second one from [google maps](https://www.google.com/maps/place/Hakamets%C3%A4+B/@61.4932347,23.8149046,17z/data=!4m8!3m7!1s0x468edf6069810c3f:0x4b54b18cf4633909!6m1!1v4!8m2!3d61.4927787!4d23.817596!16s%2Fg%2F11ngkjhlf3)

<img width="379" alt="image" src="https://user-images.githubusercontent.com/49764796/235147183-2970af54-1bd4-4922-9466-045e830b64a3.png">

<img width="308" alt="image" src="https://user-images.githubusercontent.com/49764796/235147104-17f471bf-76b1-4b03-b942-72e92f9c405d.png">

**Comment by optionsome** [comment]
Hi, thank you for informing about this issue. We will investigate what is causing it.
