### ISSUE TITLE
Digitransit-ui drains battery when left open in the background on Android

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#474]
On Android, digitransit-ui drains battery pretty fast when it is left opened in the background or with the phone screen off. Tested in Firefox, Chrome and installing digitransit-ui as a webapp. 

I have to manually close it for the drain to stop.

**Comment by tuukka** [comment]
Thanks for the report! We haven't noticed this ourselves, so this behaviour may depend on the exact phone and browser versions.

E.g. we have GPS positioning on and display the current position on the map with the animated marker. At least on Nexus 5 and Chrome, the GPS turns off automatically when I switch to home screen. I hope it's the same with the animation.

Some other features that may consume battery in the background:
* MQTT connection for realtime data subscriptions
* Automatically refreshing views like the Nearby tab

These should all be automatic, but if this is not the case for some system versions, then we should implement manual power saving with e.g. https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by kalon33** [comment]
On a LG G4 with Android 6.0 this doesn't seem the case, as both Chrome and Firefox are reported (in the battery menu) as high level battery users, only when digitransit is in use. Isn't GPS use not accounted to browsers usually (which could mean that not only positioning is involved)? For Chrome I have other tabs running, so it's difficult to be 100% sure that it is due to digitransit, but in Firefox, that was the only tab running. When I go back to home screen, with both browsers, positioning is still in use (logotype on the top bar), until I kill the relevant tab. 

MQTT can be excluded in my situation as I've no realtime data in my digitransit instance. 


----- Mail original -----

De: "Tuukka Hastrup" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com> 
Envoyé: Lundi 4 Avril 2016 15:34:10 
Objet: Re: [HSLdevcom/digitransit-ui] Digitransit-ui drains battery when left open in the background on Android (#474) 



Thanks for the report! We haven't noticed this ourselves, so this behaviour may depend on the exact phone and browser versions. 

E.g. we have GPS positioning on and display the current position on the map with the animated marker. At least on Nexus 5 and Chrome, the GPS turns off automatically when I switch to home screen. I hope it's the same with the animation. 

Some other features that may consume battery in the background: 

    * MQTT connection for realtime data subscriptions 
    * Automatically refreshing views like the Nearby tab 


These should all be automatic, but if this is not the case for some system versions, then we should implement manual power saving with e.g. https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by kalon33** [comment]
Seems to not happen anymore, closing.
