### ISSUE TITLE
Broken DepartureRow links as trip URIs are not encoded

### ISSUE THREAD

**Issue by hbruch** [HSLdevcom/digitransit-ui#4904]
The Baden-Wuerttemberg GTFS-Feed [bwgesamt](https://www.nvbw.de/fileadmin/user_upload/service/open_data/fahrplandaten_mit_liniennetz/bwgesamt.zip) has tripIds containing hashes, e.g. `tub-9-003-1-5-9-H-4-Special#3612-32-64`

## Expected behaviour:
`DepartureRow` links to the trips encode these URIs properly.

## Observed behavior
[DepartureRow](https://github.com/HSLdevcom/digitransit-ui/blob/5fb849161dba7e5feecf8f90d7d0fc5d7f5980e4/app/component/DepartureRow.js#L103) does not encode the URI. In consequence the id substring after the hash is dropped and no trip stop list is displayed:

<img width="512" alt="image" src="https://github.com/HSLdevcom/digitransit-ui/assets/2187389/e8d6e6fe-6f3d-448e-a9f6-b3fad5da86fd">

## Suggestion

The line should read:
```
<Link to={`/${PREFIX_ROUTES}/${encodeURIComponent(departure.trip.pattern.route.gtfsId)}/${PREFIX_STOPS}/${encodeURIComponent(departure.trip.pattern.code)}/${encodeURIComponent(departure.trip.gtfsId)}`}
 ```

**Comment by vesameskanen** [comment]
fixed.
