### ISSUE TITLE
FeatureRequest: MessageBarMessage links should open in new window

### ISSUE THREAD

**Issue by hbruch** [HSLdevcom/digitransit-ui#4971]
We received the wish that [links in MessageBarMessage](https://github.com/HSLdevcom/digitransit-ui/blob/c5043de37fccccbf318facb1feed234a764a22e5/app/component/MessageBarMessage.js#L25-L27) should not be opened in the DT browser tab but a new window.

Is this true for HSL also and would you accept a PR for this?

**Comment by vesameskanen** [comment]
We will find out what HSL thinks about it. It may be that PR should make link behavior configurable instead onf changing it.

**Comment by vesameskanen** [comment]
There was a discussion and conclusion is that all external links should open in a new window,
