### ISSUE TITLE
Conflicting versions for react-autosuggest

### ISSUE THREAD

**Issue by hbruch** [HSLdevcom/digitransit-ui#5006]
While `package.json` has fixed the version of `react-autosuggest` to `10.0.3`, `digitransit-component/package.json` and `digitransit-component-autosuggest-panel/package.json` have it fixed to 10.0.0.

`digitransit-component-autosuggest` and `digitransit-component-datetimepicker` only require compatible version `^10.0.0`. 

I suggest to use compatible `^10.0.0` everywhere and rely on `yarn.lock` to fix versions.

**Comment by vesameskanen** [comment]
I added a fix into https://github.com/HSLdevcom/digitransit-ui/pull/4999 . Will be merged into v3 in the near future. Thanks for  pointing out the error.
