### ISSUE TITLE
GraphQL Server Error: Exception while fetching data (/plan) : Allowed bicycle rental networks must not be empty.

### ISSUE THREAD

**Issue by larsschwarz** [HSLdevcom/digitransit-ui#5027]
I just started with Digitransit UI and set up an instance that doesn't use the whole/original Digitransit archirecture. However I do use the latest OTP (2.6.0) from the HLSdevcom repo and the latest Digitransit UI, I just don't use the HLSdevcom tileserver (but tileserver-gl instead). 

I added a Nextbike rental gbfs feed and stations and availability show just fine on the map. Clicking a rental station also shows all details (id, name, available bikes). Stations nearby also works as expected.

The OTP debug client returns a bike_rental route just fine.

However whenever I try a citybike routing I'm seeing the route itself on the map, but along with the "falling guy illu". 

Console shows a 

`GraphQL Server Error: Exception while fetching data (/plan) : Allowed bicycle rental networks must not be empty.`

error followed by 

`TypeError: Cannot read properties of null (reading 'network')`

I doublechecked the pbf vector map for realtimeRentalStations and this does include the network id/name (nextbike_wo). 

I added 

`allowedBikeRentalNetworks: ['nextbike_wo'],`

but this doesn't change anything.

Not sure whether this is related to the Digitransit UI or OTP, but since the OTP debug client returns a bike rental route just fine I thought to post this here. I'm a newbie in regards to Digitransit UI and OTP as well, so this probably ain't a bug at all, but I have no idea how to debug this.

**Comment by vesameskanen** [comment]
Hi! Sorry for late reply. Do you still have this problem? I suspect some sort of configuration error.  I could take a look what goes wrong if you send me your data and configurations.

**Comment by larsschwarz** [comment]
Hi Vesa. Currently running OTP 2.5 and a fork of Digitransit UI on the instance that had this issue. I'll set up the same config that had the issue on a different instance and share the details here afterwards.
