### ISSUE TITLE
Problems around stops (display, details)

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#514]
Using useVectorTiles: false (as I don't have stop map or citybike map servers outside OTP), I got a few problems. Let's see:

![screenshot_2016-04-15-22-58-36](https://cloud.githubusercontent.com/assets/460731/14575011/428b6fe6-035f-11e6-8bc9-ab9009e7d155.png)

For some stops, I don't have next departures or some indication there are none (it's only plain grey, without spinner) and at every stop I see a "undefined" text below, sometimes replacing stop name like here:

![screenshot_2016-04-15-22-57-11](https://cloud.githubusercontent.com/assets/460731/14575058/afd296c4-035f-11e6-917d-5502a2beeff9.png)

This time, I have next departures at stop. I really don't know why it works sometimes and sometimes not (maybe when there's no more buses for today? But I got no message saying no buses!). But lot of space is lost on the left and on right of the screen, cutting bus destination. There's also a huge free space on the bottom after next departures... that should probably be better used.

Do you have some solutions for my problems?

**Comment by tuukka** [comment]
You seem to be using terminals, we never show that type of marker (although I'm not sure why - I think you can configure the zoom levels). We only show buses in today's schedule - lack of infinite scroll could be filed as an issue. You have very long headsigns - maybe break them into multiple lines here if what's visible is not enough? Of course, you could also disable the fade-out.

**Comment by kalon33** [comment]
@tuukka I didn't even know I've been using terminals. Is there a way to change this?

For the headsigns fade-out, I don't think it is a problem, just that it take to my mind much more space than needed.

Infinite scrolling would be great, but when the list is short, there should be more map space and less empty grey zone at the bottom, it would be nicer to the eye. Maybe there should be a message that this is the last one vehicle of the service (schedule) though? That's useful to know that you have to get it to go back home!
