### ISSUE TITLE
Unable to Start New v3 Digitransitui on Ubuntu

### ISSUE THREAD

**Issue by dgrozev96** [HSLdevcom/digitransit-ui#5140]
I am encountering an issue when trying to start the development server for the new v3 digitransitui on my Ubuntu machine. I have the following setup:

Operating System: Ubuntu Linux
Node Version: 20.13.1
Yarn Version: 3.4.1
Watchman: Installed
GCC Version: 4.6
Steps to Reproduce:

Run yarn install - Success
Run yarn setup - Success
Attempt to start the development server with yarn run dev
Expected Behavior: The development server should start successfully, and I should be able to access it at http://localhost:8080.

Actual Behavior: When I access http://localhost:8080, I receive an error. Below is the complete log output from the terminal:
Error: connect ECONNREFUSED 127.0.0.1:9000

The log:
https://smalldev.tools/share-bin/DGjbF3Fj

I would appreciate any guidance on troubleshooting this issue or any known compatibility issues with my current setup.
Thank you for your assistance!

**Comment by vesameskanen** [comment]
Does it help if you change devserver host back to '0.0.0.0' here:

https://github.com/HSLdevcom/digitransit-ui/blob/v3/webpack.config.babel.js#L334
