### ISSUE TITLE
[regression] can't retrieve itinerary details in digitransit-ui

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#529]
With latest Tuesday 26th April changes, it is not possible to display itinerary details anymore (was possible just before these commits on 25th evening, I tested it). Spinner is just turning again and again... Setting origin and destination and retrieving itinerary list is possible, but not displaying the detailed view.

Is this possible to get a look at it? I reviewed my diff between master and my local repo, and I only have changes in config.default.coffee and in app/util/leg-text-util.js (to disable line name replacement by "M" for subway lines).

Thanks!

**Comment by samuliheljo** [comment]
Do you have latest master from:
- hsldevcom/digitransit-ui
- hsldevcom/opentripplanner

If not could you try with these latest versions

**Comment by kalon33** [comment]
@samuliheljo sure, I have latest of both of them from yesterday evening.

**Comment by samuliheljo** [comment]
Could you add link to url where UI runs?

**Comment by kalon33** [comment]
It seemed to happen with one of the commits after #527 merging. I tested immediately after this merge and it was working properly.
@samuliheljo http://transit.acolytesanonymes.org . It is not restricted via a polygon as you did elsewhere (because I didn't found a proper polygon to set yet), you need to search itineraries around or into Paris (France) to get results.

**Comment by hukka** [comment]
Triaged and tracked at https://digitransit.atlassian.net/browse/DT-955, it is related to the update-dependencies -branch

**Comment by hukka** [comment]
Fixed, will be merged soonish. Thanks for reporting.

**Comment by kalon33** [comment]
@hukka You're welcome, thanks for fixing this :)
