### ISSUE TITLE
Digitransit should use GTFS route_color in itinerary summary, details and on the map

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#537]
Using official line colors in Digitransit as in GTFS route_color should make it more intuitive to know which lines you are travelling with. It would also be great to provide an override when no color is set in the GTFS. 
BTW, it would also comply with transit authority color schemes, that the user is used to find in everything relative to the transit lines.

**Comment by tuukka** [comment]
This should be easy enough for you to implement yourself for Paris: in our GraphQL API, routes have `color` and `textColor` that you could add to the queries that currently include `mode`.

**Comment by AlexLoyko** [comment]
Would you like help with this?

**Comment by kalon33** [comment]
@AlexLoyko Why not please, I'm currently busy with other things for my work (far away from transit stuff), and I don't have enough time regarding my skills to understand how the code would work...

**Comment by AlexLoyko** [comment]
I am working on this issue, and faced a problem that once I enter "color" as one of the route's attributes in the request, it returns null. So, I went ahead and figured out where the color is set in the scss. That was the _helper-classes.scss to which I have access to any DOM element. However, it just does not feel right to search through all the components to find every line segment and set color(or add an extra property to it to achieve this issue). My feeling is that we could just modify the QL request with the color attribute for a planner that returns the actual color and set it. Am I right regarding the GraphQL part or I need to search through every element of the UI and add an extra prop color which I set based on my mode(subway in our case) and subway code by updating the _helper-classes.scss?
Thanks in advance!

**Comment by AlexLoyko** [comment]
To make it shorter and more clear, what would be the best way to update colors programmatically, either as a component prop in a Relay store or some other way?

**Comment by tuukka** [comment]
@AlexLoyko The schema looks correct (type Route with fields color and textColor). I don't see a reason to change it. The backend implementation is here: https://github.com/HSLdevcom/OpenTripPlanner/blob/master/src/main/java/org/opentripplanner/index/IndexGraphQLSchema.java#L1610

Where the UI currently queries GraphQL for Route mode and shortName or puts them into props, I think it should additionally handle the colors. When rendering DOM, the code can set element inline styles, if the colors are not null. If the colors are null, there is no need to set inline styles and theme scss should apply as it does now.

There may be additional complications that I'm not taking into account though.

**Comment by AlexLoyko** [comment]
Thank you very much! On it.

**Comment by AlexLoyko** [comment]
@tuukka 
I have got the color from the queries and successfully updated the icons backgrounds and polylines on the map with corresponding color. The lines in the SummaryRow are the thing I can't find a way to update. What style sheet does this value correspond to?

https://github.com/HSLdevcom/digitransit-ui/blob/b328365c0df03d6154fb6edcc32fe2f52e4c1f81/app/component/SummaryRow.js#L36

It feel like the line is hardcoded somewhere in the css and without this the line in the link it won't get drawn.

**Comment by AlexLoyko** [comment]
@tuukka 
I got the icons and the polyline on the map with corresponding colors. However, the lines(legs) in  SummaryRow.js are seemed to be hardcoded in this css https://github.com/HSLdevcom/digitransit-ui/blob/b328365c0df03d6154fb6edcc32fe2f52e4c1f81/app/component/summary-row.scss#L160.

In order to draw those lines with corresponding colors, would it be acceptable to simply draw another line on top of the default one without touching the base code?

**Comment by tuukka** [comment]
I don't see the hardcoding - do you mean the color of `.line &:after`? If you set color via inline style where SummaryRow.js sets `cx('line')`, doesn't that do the trick?

**Comment by AlexLoyko** [comment]
It looks like it is impossible to use inline css for pseudo-elements. Please correct me if I am wrong.

**Comment by kalon33** [comment]
Fixed by #1553

**Comment by kalon33** [comment]
Thanks @AlexLoyko :)
