### ISSUE TITLE
Schedules missing after midnight

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#545]
It seems that some part of the system (probably the backend?) is not aware of that in the HSL world the day changes at 4 am.

If you click a bus stop around midnight, it only shows the departures that will arrive after 4 am although there would be connections between 12 pm - 4 am.

I put the issue here because I found it by using the UI and didn't have enough time to check the reason and the correct component.

**Comment by hannesj** [comment]
This is covered by the issue [DT-259](https://digitransit.atlassian.net/browse/DT-259). As a stopgap measure we could always load the previous and next service dates to give proper coverage around midnight.

**Comment by hannesj** [comment]
This was fixed in https://github.com/HSLdevcom/digitransit-ui/pull/1247
