### ISSUE TITLE
Menu obscures screen on some old browsers

### ISSUE THREAD

**Issue by hugovk** [HSLdevcom/digitransit-ui#552]
Nokia 808 / Opera Mobile 12
1. Visit https://dev.hsl.fi/kaupunkipyorat/

Expected result: Can see the map.

Actual result: The side menu fills most of the screen and cannot be hidden. None of the links do anything. See screenshot.

![scr000059](https://cloud.githubusercontent.com/assets/1324225/14966343/8291d7d4-10ba-11e6-9f98-c170bcc824fd.jpg)

(Also, these merged typos are still visible: https://github.com/HSLdevcom/digitransit-ui/pull/421 https://github.com/HSLdevcom/digitransit-ui/pull/423)

**Comment by hannesj** [comment]
Related to [DT-979](https://digitransit.atlassian.net/browse/DT-979). As for the typos, I'll need to check what happened with them.

**Comment by hannesj** [comment]
Hi,

It seems Opera 12.0 does not have some of the required features implemented. Could you try to upgrade to a newer version.

**Comment by hugovk** [comment]
Unfortunately Opera 12.0 is the latest version available for Symbian phones.

I also tried the built-in Web (NokiaBrowser/8.3.2.21) browser and Opera Mini 7.1.32453, but they had the same problem.

What features are missing in Opera 12.0?

(And those merged typos are still visible: #421 #423)

**Comment by hannesj** [comment]
At least CSS Transforms that are used by [material-ui](https://github.com/callemall/material-ui) seem to be only supported from Opera Mobile 12.1 (Presto 2.11)

Also, Opera Mini isn't one of our supported browsers, so we won't actively be fixing this by ourselves, but accept PR:s if anybody want's to help.

**Comment by hugovk** [comment]
Sure, I don't expect Opera Mini support, but one of the other two (I prefer Opera Mobile) would be great.

**Comment by hugovk** [comment]
I hear the new Journey Planner is being launched soon, which is great where it works, but any news on this? 

The new https://beta.reittiopas.fi and https://beta.digitransit.fi look like this on my phone and I don't want to be stuck hoping for a bus when it's -15C :)

![image](https://cloud.githubusercontent.com/assets/1324225/22363896/448a1e02-e476-11e6-9d84-f212f4503984.png)

**Comment by samuliheljo** [comment]
Hi,
Unfortunately at the moment your mobile device + browser combination is not supported.
After we release new Reittiopas, old reittiopas will be still available for some time.

**Comment by hugovk** [comment]
What phones/browsers do you support?

How long do you think the old Reittiopas will still be available?

**Comment by hannesj** [comment]
Currently we support recent Blink/Webkit/Gecko-based browsers, IE11 and MS EDGE.

**Comment by hugovk** [comment]
I've tried with the built-in, Webkit-based Web browser, but get:

![image](https://cloud.githubusercontent.com/assets/1324225/22370716/7b4a7f20-e49b-11e6-98c9-5f7597ac2058.png)

And when scrolling down, I see the page, but then the menu jumps back down again:

![image](https://cloud.githubusercontent.com/assets/1324225/22370729/8ad7d6cc-e49b-11e6-8eb6-446fbaef3f30.png)

This is with Webkit 535.1. Is this too old? (My up-to-date desktop Chrome is 537.36.)

Thanks.

**Comment by hannesj** [comment]
That version of Webkit corresponds to Chrome 14, which was released over 5 years ago, and can hardly be described as recent. Based on the current configuration, something around Chrome 21 meets the current requirements. It seems that the issue might be with the [material ui](http://www.material-ui.com/#/) library used. Could you test that the drawer works on their site (http://www.material-ui.com/#/components/drawer).

**Comment by hugovk** [comment]
Yeah, it's not recent :)

http://www.material-ui.com/#/components/drawer just loads as a blank white page.
