### ISSUE TITLE
[regression] Current location doesn't work anymore on Chrome (Android)

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#554]
Under Android (6.0 at least), latest Chrome (50.0.2661.89), Digitransit-ui is not able to use current location anymore (tested on two different phones). Splash screen is immediately skipped and fallback location displayed. This changed recently and doesn't affect Firefox mobile for Android. This doesn't affect Chromium 49.0 version either.

My guess is that something changed recently in latest Chrome version (between 49 and 50) that broke it, but I'm not the expert :)

**Comment by hannesj** [comment]
Chrome 50 [disabled geolocation](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en) from insecure origins, so you need to serve the site from a HTTPS-enabled server and force the clients to use that. Closing as this is not specific to the ui, but rather server configuration.
