### ISSUE TITLE
Route page

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#59]
- [x] Layout as defined in concept
- [x] show all line stops
- [x] Clicking stop takes user to stop page
- [x] Show vehicles in realtime on "road"
- [x] Clicking vehicle takes user to departure page
- [x] Line can be added as favourite
- [x] Switch line direction

Out of scope for this task:
- Line map #60 
- Timetable #61

**Comment by JariHonkonen** [comment]
No addresses, Data source problem
No min. amounts. Data source problem. Needs concepting.

No dotted line
Wrong vehicle icon
Vehicle icon positioning needs better resolution, ->on stop or between stops.

Returning route and route variations needs concepting (stops have different number/name, may have less or more stops)
