### ISSUE TITLE
[regression] Not possible to set arrival point using the upper bar anymore

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#601]
Using latest Digitransit master, it is not possible anymore to use the upper bar at all, setting an origin or destination point (can't click on PC or touch on mobile it to be able to type something). 

This was working using last week code.

**Comment by samuliheljo** [comment]
Yikes! That's a bug. we'll check it out.

**Comment by samuliheljo** [comment]
Fixed

**Comment by kalon33** [comment]
Thanks :)
