### ISSUE TITLE
Routing seems to prefer "first possible departure" instead of "last possible departure"

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#619]
At least in some cases, reittiopas seems to prefer the “first possible departure” instead of “last possible departure”. E.g., if you make the search below both with start time 14:00 and 16:00, you’ll notice that the second result in 14:00 departing 14:50 is in “Kajaani” at the same time as the first result in 16:00 search departing 16:11:
https://beta.digitransit.fi/reitti/H%C3%84MEENLINNA%3A%3A61.002225%2C24.478305/Kajaani%2C%20Kajaani%3A%3A64.226734%2C27.728047 . Effectively, the user has to spend almost 1,5 hours more in transit waiting rather than spending that time at the starting location.

**Comment by samuliheljo** [comment]
Adding some images:

<img width="894" alt="screen shot 2016-05-23 at 15 31 56" src="https://cloud.githubusercontent.com/assets/1298522/15470848/8bcbfb4e-20fb-11e6-82cb-6cb86967968d.png">

<img width="897" alt="screen shot 2016-05-23 at 15 32 06" src="https://cloud.githubusercontent.com/assets/1298522/15470852/904c97be-20fb-11e6-9777-f44b937abd3f.png">

**Comment by samuliheljo** [comment]
So, It would be nice if "14:00 example" would include 16:11 --> 23:17

**Comment by hannesj** [comment]
This is partially caused by [this](https://github.com/HSLdevcom/digitransit/wiki/FTA-GTFS-problems#42-reittiduplikaatit-not-ok) and [this](https://github.com/HSLdevcom/digitransit/wiki/FTA-GTFS-problems#43-reittiduplikaatit-eri-aineistoista-not-ok) issue in the data provided to us. Another way to fix this would be to improve the performance of the routing nodes or increase the timeout (which is already quite long).

**Comment by apkoponen** [comment]
> So, It would be nice if "14:00 example" would include 16:11 --> 23:17

I actually think that it would be better if the "14:00" example would only include 16:11 --> 23:17 and not 14:48 --> 23:17, because they share the same train for the rest of the journey so it's better in terms of UX to show only the ones that are actually different in terms of arrival time.

**Comment by vesameskanen** [comment]
New OTP2 routing fixes such errors.
