### ISSUE TITLE
Disallow routing from the same place to and from

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#639]
Backend fails (starts throwing 500's) if origin and destination are the same.

GraphQL response:
`{"data":{"viewer":{"_plan2LB1y7":null}},"errors":[{"exception":{"stackTrace":[{"methodName":"sliceStates","fileName":"GraphPathToTripPlanConverter.java","lineNumber":232,"className":"org.opentripplanner.api.resource.GraphPathToTripPlanConverter","nativeMethod":false},{"methodName":"generateItinerary","fileName":"GraphPathToTripPlanConverter.java","lineNumber":146,"className":"org.opentripplanner.api.resource.GraphPathToTripPlanConverter","nativeMethod":false},{"methodName":"generatePlan","fileName":"GraphPathToTripPlanConverter.java","lineNumber":85,"className":"org.opentripplanner.api.resource.GraphPathToTripPlanConverter","nativeMethod":false},{"methodName":"plan","fileName":"GraphQlPlanner.java","lineNumber":40,"className":"org.opentripplanner.index.GraphQlPlanner","nativeMethod":false},{"methodName":"lambda$new$0","fileName":"IndexGraphQLSchema.java","lineNumber":544,"className":"org.opentripplanner.index.IndexGraphQLSchema","nativeMethod":false},{"methodName":"resolveField","fileName":"ExecutionStrategy.java","lineNumber":40,"className":"graphql.execution.ExecutionStrategy","nativeMethod":false},{"methodName":"call","fileName":"ExecutorServiceExecutionStrategy.java","lineNumber":50,"className":"graphql.execution.ExecutorServiceExecutionStrategy$1","nativeMethod":false},{"methodName":"call","fileName":"ExecutorServiceExecutionStrategy.java","lineNumber":47,"className":"graphql.execution.ExecutorServiceExecutionStrategy$1","nativeMethod":false},{"methodName":"run","fileName":"FutureTask.java","lineNumber":266,"className":"java.util.concurrent.FutureTask","nativeMethod":false},{"methodName":"runWorker","fileName":"ThreadPoolExecutor.java","lineNumber":1142,"className":"java.util.concurrent.ThreadPoolExecutor","nativeMethod":false},{"methodName":"run","fileName":"ThreadPoolExecutor.java","lineNumber":617,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","nativeMethod":false},{"methodName":"run","fileName":"Thread.java","lineNumber":745,"className":"java.lang.Thread","nativeMethod":false}],"suppressed":[]},"errorType":"DataFetchingException","message":"Exception while fetching data: org.opentripplanner.routing.error.TrivialPathException"}]}`

Test it out:
https://dev.digitransit.fi/reitti/Puutarhaoppilaitos%3A%3A61.116357%2C24.325225/Puutarhaoppilaitos%3A%3A61.116357%2C24.325225

I can confirm that this happens also with the latest Docker image (don't know if it's the same as used with dev-version).

**Comment by Macroz** [comment]
Yes this is well known for us, but so far there is no design for the solution, so it's not on the backlog. At least now the application behaves better when it occurs, but an improved design is needed also in the long run.

**Comment by Macroz** [comment]
See also this PR https://github.com/HSLdevcom/OpenTripPlanner/pull/60

**Comment by Macroz** [comment]
The change should be deployed in dev already.

**Comment by Macroz** [comment]
Shoudl be deployed to beta so go ahead and test!

**Comment by apkoponen** [comment]
Good! Closing.
