### ISSUE TITLE
floating "from" box steals focus, won't allow scrolling map beyond visible area after tapping

### ISSUE THREAD

**Issue by esuomi** [HSLdevcom/digitransit-ui#645]
### Preconditions:
Location services are *on*.

### Steps to reproduce:
 1. Tap the pulsating icon representing "from" position
 2. Scroll screen to any direction so that the icon is not visible on the screen anymore

### Expected behaviour
Map allows me to scroll wherever I want to.

### Actual behaviour
Map scrolls back to position where "from" icon is fully visible again.

### Additional info
This behaviour seems to be mobile only, more specifically iPhone 6 with latest&greatest iOS (_9.3.something? just updated_). On desktop with mouse I can't reproduce this at all.

### How I discovered this
I was trying to look up a bus route from nearby grocery store *just* out of view to a friends place a bit further away.

**Comment by Macroz** [comment]
Thanks for the report! We have noticed this, but it seems our first fix did not complete resolve the case. There is a JIRA issue now here https://digitransit.atlassian.net/browse/DT-1091 for the follow-up.

**Comment by Macroz** [comment]
This is now deployed to dev.

**Comment by esuomi** [comment]
Confirmed to work 👍

**Comment by Macroz** [comment]
Also now in the beta environment, closing this.
