### ISSUE TITLE
Adding query support for actual IDs instead of GTFS ids.

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#671]
Currently the id parameter for GraphQL queries to use is the gtfsId of the trip, stop etc. This is quite counter-intuitive. What is the reason behind this behaviour and is adding support for the actual graphQL IDs something you've considered?

**Comment by tuukka** [comment]
You can use the GraphQL id in the `node` query.

**Comment by apkoponen** [comment]
Aight, missed that in the docs!
