### ISSUE TITLE
Two search fields

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#71]
Create a new component that will be our <Search/> component. The goal is to gradually make this work with all user stories that will be defined. 

For now, component should have following props:
- [ ] onSelect(selectedValue, lat, lon) --> Called when value is selected in component
- [ ] useCurrentLocation --> Whether component should render user's current location or not
- [ ] initialValue --> Initial value and location coordinates
- [ ] placeholder --> What to show when field is empty

**Comment by tpievila** [comment]
https://github.com/HSLdevcom/digitransit-ui/tree/two_search_fields

**Comment by samuliheljo** [comment]
Some comments in Finnish:

Yleiset hakulaatikkoon liittyvät:
- SAMULI: "harmaassa laatikossa" teksti on hieman tiukan oloinen, katsotaan ville leiska
- TOMI: "harmaassa laatikkossa" oleva "oma sijainti" ei tule käyttöliittymään
- TOMI: Suurennuslasin klikkauksen tulee tehdä haku, nyt se ei sitä tee
- TOMI: valittu sijainti pitää olla muutettavissa. Käytetään kirjoitetulle osoiteelle puhtaasti input kenttää. Ei "harmaata laatikkoa"

Summary sivuun liittyvät:
- TOMI: Summary sivulta palatessa back-painikkeella ja sitten poistettaessa määränpää etusivulta, tekee käyttöliittymä haun
- TOMI: Summary sivun back ei toimi, jos lähtöpaikka ja määränpää vaihdetaan pari kertaa keskenään

**Comment by samuliheljo** [comment]
Could you verify one thing for me:
1) Remove node_modules
2) Run npm cache clean
3) Run npm install

Then try to start application. What happens?

**Comment by hukka** [comment]
Did git clone; npm install; npm run dev; cannot replicate the issue.
