### ISSUE TITLE
View where PRs would be accepted

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#722]
What view would you suggest I should start working on? I'd rather do new components, but can also refactor / restyle existing parts of the app.

A-P

**Comment by hannesj** [comment]
Hi,

At the moment, there are not that many completely new parts that have been properly designed. Some interesting issues for you might be:

 - [Terminal page](https://digitransit.atlassian.net/browse/DT-1112)
 - [Removal of favourite](https://digitransit.atlassian.net/browse/DT-1113)
 - [Printable itinerary](https://digitransit.atlassian.net/browse/DT-928)
 - [Arriving vehicle](https://digitransit.atlassian.net/browse/DT-1117)

Please comment if any of these interest you. As they are not in the current sprint, which lasts until 4.7, feel free to start working on any of those. If you need more information about any of those we are more than happy to help out. Of course you are free to work on any other issue you find in JIRA, but those might need a bit more discussion how to proceed with.

**Comment by apkoponen** [comment]
I did today some work on the "Arriving vehicle". We can continue discussion in my PR, where I have added a few questions:

**Comment by apkoponen** [comment]
In addition, I would be interested in the "Terminal page", but I'd need more info in order to be able to start with it.

Removal of favourite seems otherwise straightforward, but "long tap" in browsers seems to be quite hard to actually implement reliably?

**Comment by apkoponen** [comment]
+ Long tap does not work on the Desktop, which we'll eventually want to support, I suppose?
