### ISSUE TITLE
Route Schedule header broken

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#726]
The header padding is acting out for some reason, which causes the header to height to bee too small.

https://dev.reittiopas.fi/linjat/HSL:1066A:0:01

<img width="394" alt="screen shot 2016-06-15 at 14 56 03" src="https://cloud.githubusercontent.com/assets/5046650/16078792/68d7d49e-3309-11e6-95fc-51813c998ab6.png">

**Comment by hannesj** [comment]
Hmm, which browser are you using, seems to work fine with all of mine (except for firefox which has still native dropdown buttons, I should look into that)

![screen shot 2016-06-15 at 15 15 51](https://cloud.githubusercontent.com/assets/698100/16079432/35ff8186-330c-11e6-8319-f4b255f9c807.png)

**Comment by apkoponen** [comment]
It was on OS X with Chrome 50. something. The view did not work even after force refreshing. However, my Chrome just updated to the latest version and everything works fine. Closing.
