### ISSUE TITLE
New route schedule viewer only displays part of the departures

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#729]
When looking at some line timetable, I only get part of the departure/arrivals when there are multiple possible destinations for a line (and so multiple stops patterns), looking at a stop where both destinations are possible in the same GTFS direction_id. I'm not able to select stops from one of the two patterns as origin or destination stops (and it's not the same depending on the stop direction_id I choose)

**Comment by hannesj** [comment]
This will be worked on in [DT-1155](https://digitransit.atlassian.net/browse/DT-1155), where a dropdown for selecting the pattern will be implemented.

**Comment by kalon33** [comment]
Thanks @hannesj, what is the time schedule for this (Sprint 16 doesn't talk to me as I can't find Sprint dates)? 


----- Mail original -----

De: "Hannes Junnila" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 16 Juin 2016 10:21:42 
Objet: Re: [HSLdevcom/digitransit-ui] New route schedule viewer only displays part of the departures (#729) 



This will be worked on in DT-1155 , where a dropdown for selecting the pattern will be implemented.

**Comment by hannesj** [comment]
Unfortunately Atlassian changed the JIRA agile features to be visible only after logging in. Sprint 19 is 15.6-4.7.

**Comment by kalon33** [comment]
Is this possible to display in route timetables departures/arrivals of vehicules that are on the same line but with a different stop pattern between departure and arrival points?
