### ISSUE TITLE
Protips for speeding up development?

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#738]
Currently, it takes 5-10 seconds in my computer for the app to boot after a change in the JS files. This slows down the development. Webpack's Hot Module Replacement does not really seem to work other files than styles. This is especially annoying when making changes to things in modals/pop-ups, which have no direct route.

In addition, cjsx2es6 does not conform to es-lint, which causes extra work, when transforming files. E.g. Strings use " instead of '. Is there anything we can do about this?

**Comment by Macroz** [comment]
For me also the hot replacement takes several seconds.

You can run `eslint --fix` to help with some of the trivial code transformation problems.

**Comment by apkoponen** [comment]
OK, thanks for the info! I investigated Hot Module Replacement a bit further for another project and seems that it won't currently work with Stateless Functional Components (which Digitransit UI uses a lot).

I'll close this issue now.
