### ISSUE TITLE
Recalculating route 'Now' does not update start point for current position

### ISSUE THREAD

**Issue by anttivs** [HSLdevcom/digitransit-ui#749]
After routing using the current position, the 'A' and 'B' markers seem to be fixed. Clicking on the 'Now' button to recalculate the route should, in my opinion, update the start point to the current position. At least my use case is that while I am walking towards the start point, I'd be able to get new routing estimates from my current position.

**Comment by tuukka** [comment]
Thanks for reporting, we didn't seem to have this on the backlog. In some earlier discussions, I recall the result was that we should do this if 'A' or 'B' is "Your current location".

An additional way that I think we should support is via popup menus when you click the position or A/B markers, but this remains to be designed.

**Comment by Macroz** [comment]
I've gotten this request as well. I created a task for this. We'll see where it gets prioritized.

https://digitransit.atlassian.net/browse/DT-1179

**Comment by tuukka** [comment]
This issue is resolved: "Your current location" updates when you click "Now".
