### ISSUE TITLE
Disruption info

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#75]
![diruption](https://cloud.githubusercontent.com/assets/1298522/9541822/753eefa4-4d74-11e5-9212-8ac20637b395.png)

Main idea:
Show disruption info popup when front page icon is clicked

Before starting:
- [x] Check what react popup components are available. At least see these: http://react.rocks/tag/Popup then check for other alternatives.

Popup logic:
- [x] When application loads do query to fetch disruption info. If this data is available through GraphQL api, use that. If not then fetch it from somewhere else and put it in a flux store
- [x] If there are no disruption information icon should remain gray
- [x] If there is disruption information available icon should be in yellow color
- [x] When user clicks on icon, open disruption info popup
- [x] Show popup contents as defined in concept

Stop card logic:
- [ ] Highlight those lines on stop card that have disruption information like so:
![hilight](https://cloud.githubusercontent.com/assets/1298522/9542191/44807948-4d77-11e5-8047-810b376593f3.png)

**Comment by MikaelStenstrand** [comment]
If no disruption information is available, the icon will stay gray and the modal will not be shown on click event.

**Comment by MikaelStenstrand** [comment]
The style of highlighting a line-row is done (.disruption). However, the logic of highlighting these lines is no implemented in this task

**Comment by samuliheljo** [comment]
Let's do add highlighting for trips in stop card

**Comment by MikaelStenstrand** [comment]
Added the feature of highlighting trips in stop card

**Comment by samuliheljo** [comment]
Disruption info needed changes:
1) When application is launched with "npm run dev" then "poikkeusinfo" text is drawn with color that is not visible (in popup)

2) Disruption info shows lines as "1003", "1002". Why is that and can we do something about it?

3) I suggest that we add something like this:
.transport.disruption {
  margin-bottom: 1px !important;

Or similar functionality where we get slight space between transports.

4) Why "disruption info yellow" is not rgba(254, 232, 127, 1)? I got this when transforming "#FEE87F" to rgba
Now It seems to be rgba(254, 209, 0, 0.5). To my eye it is different than in invision mockup.
--

When these have been resolved, please merge to master

**Comment by MikaelStenstrand** [comment]
Done.
reagarding 2) Only route_id is available in disruption info at the moment.
