### ISSUE TITLE
"Buy ticket" button not visible

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#751]
Using default config, I activated ticket price display (and it is properly displayed). Button to buy a ticket that should redirect to the webshop to buy a ticket is here (I can find the link), but not visible (like if it was white on a white background).

Please fix :)

**Comment by Macroz** [comment]
We do not have ticket buying enabled for the default configuration so the styles are perhaps not correct. Also the buy link is hard coded. This is not a priority for us now, so others are welcome to improve this.

**Comment by tuukka** [comment]
@kalon33 seems you can enable this feature by uncommenting code here https://github.com/HSLdevcom/digitransit-ui/blob/master/app/component/LegAgencyInfo.js#L21
