### ISSUE TITLE
[regression] Route details not available anymore

### ISSUE THREAD

**Issue by kalon33** [HSLdevcom/digitransit-ui#752]
When choosing an itinerary from summary and then clicking on one of the transit lines proposed, I can't get to route details. I have a splinner displayed, that spin undefinitely. That was properly working last week.

Please fix :)

**Comment by Macroz** [comment]
We have no known issue like this. Can you reproduce in https://beta.reittiopas.fi/ or perhaps https://dev.reittiopas.fi/ ?

**Comment by kalon33** [comment]
I can reproduce with a digitransit-ui instance that I didn't updated since half june, that I just updated and is not working properly anymore. A diff against upstream master indicates that my only changes are in config.default.coffee file, so not enough to explain this bug...

**Comment by kalon33** [comment]
@samuliheljo any idea on this?

**Comment by tuukka** [comment]
@kalon33 No idea. If you cannot reproduce this in https://beta.reittiopas.fi/ or https://dev.reittiopas.fi/ then we cannot reproduce it either.

**Comment by kalon33** [comment]
@tuukka might it be linked to Real-Time data being completely inexistant for it? My only delta with upstream digitransit is config file... Do you think you could find the problem (or try to reproduce it) using my config file (if yes, I will provide it)? 

----- Mail original -----

De: "Tuukka Hastrup" <notifications@github.com> 
À: "HSLdevcom/digitransit-ui" <digitransit-ui@noreply.github.com> 
Cc: "Nicolas Derive" <kalon33@ubuntu.com>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 11 Août 2016 17:42:37 
Objet: Re: [HSLdevcom/digitransit-ui] [regression] Route details not available anymore (#752) 



@kalon33 No idea. If you cannot reproduce this in https://beta.reittiopas.fi/ or https://dev.reittiopas.fi/ then we cannot reproduce it either.

**Comment by tuukka** [comment]
Best would be a link to your service where we can reproduce this, plus your config file.

**Comment by kalon33** [comment]
Ok nice,

So here is my config file (I changed extension to txt to be able to upload it to github)
[config.default.coffee.txt](https://github.com/HSLdevcom/digitransit-ui/files/415104/config.default.coffee.txt)

my Digitransit instance is https://transit.acolytesanonymes.org/ and OTP instance is at http://paris.acolytesanonymes.org (as you can see in the config file). The only thing I altered in the file, is my Mapzen API key.

Thanks a lot for your help :)

**Comment by kalon33** [comment]
@tuukka Did you had the occasion to have a look at it with the details I gave? I'm still experiencing it with latest master.

Thanks :)

**Comment by kalon33** [comment]
Seems to be fixed since friday, hourrah! But I have glitches in routes details (see squares on my screenshot). Do you know where it comes from?
![screenshot_2016-09-07-07-48-18](https://cloud.githubusercontent.com/assets/460731/18302722/9c76f444-74d9-11e6-8bd4-7f1d4894b478.png)
![screenshot_2016-09-07-07-48-26](https://cloud.githubusercontent.com/assets/460731/18302721/9c747052-74d9-11e6-9a8f-523395da0fe8.png)

**Comment by hannesj** [comment]
They should be removed after https://github.com/HSLdevcom/digitransit-ui/commit/0dc9bd757c594682a50b825c961d480d12985635 gets merged

**Comment by kalon33** [comment]
Problems fixed, thanks!
