### ISSUE TITLE
Suggest walking for short distances

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#762]
I was playing with the favorites functionality and set my home address to one of the locations. Of course, I wanted to see what it suggested to get home while being at home:

![hsl_reittiopas](https://cloud.githubusercontent.com/assets/2797729/16535229/830575a0-3fee-11e6-8397-1183f3e0f35f.png)

It suggests to walk 500 meters to a bus stop and then travel back to home by bus! :smile: I think there should be some kind of limit that if the distance is shorter than 300 meters (or at least if the most optimal route contains more walking than the distance between the A and B), it should suggest to walk.

**Comment by ttsirkia** [comment]
Of course, this is a bit problematic in some cases. For example, if there is a river between A and B and only limited number of bridges, it might be a good idea to take bus although the distance between the points is short but the actual route is much longer.

So, it should know the shortest viable path between the points and compare if it is shorter (and faster) to walk than take a bus, for example. This information might be hard to retrieve in some cases.

**Comment by Macroz** [comment]
Hey, thanks for the comment. We have discussed this also at length and will do something about it in the future.

Some things to consider:
- OpenTripPlanner tries to use the public transport network to give you (alternative) routes. Try searching within e.g. Suomenlinna to have more funny routes. If it happens to find a direct walking route, it will show it. But it cannot show you more than one walking route (the next best walking route is to walk 1 meter to any direction and then go back to the best walking route). So the next options must use some public transport.
- Should one walk/bicycle/car route always be shown? What is the maximum distance for it? Probably different for each mode of own transport.
- When is a route "comically bad" that it should never be shown? E.g. your case and Suomenlinna. Or try bicycle route from Tapiola to Friisilä. These routes have a train in addition to bicycling but the train route is much longer and slower.

**Comment by ttsirkia** [comment]
At least with those experiments that I did in Suomenlinna and between Tapiola and Friisilä, the first suggestion was to walk or bicicyle the whole route. The other options were much funnier. But for some reason, in the original case, it does not suggest the walking option at all.

**Comment by Macroz** [comment]
I don't know why, but it happens sometimes. For your case I do get a walking route as well, but e.g. Aleksanterinkatu 44 - Aleksanterinkatu 44 I get only trams.

**Comment by tuukka** [comment]
When there's no walking suggestion at all, then that can be considered a bug in OpenTripPlanner. We might also want to always plan another route without public transport as well to use as a baseline suggestion.

One simple definition for "comically bad": worse than another suggestion in every way: more walking, longer duration, later arrival, more waiting. This should rid us of these public transport options that lose to walking in every way.

**Comment by Caasulaitos** [comment]
I got another comically bad routing, this time alongside other completely good routings...
![screen shot 2017-05-17 at 13 30 54](https://cloud.githubusercontent.com/assets/6472267/26150017/4f18880a-3b05-11e7-9152-2a9125b368c6.png)

**Comment by vesameskanen** [comment]
OTP2 routing fixes this.
