### ISSUE TITLE
Cache CORS preflight requests

### ISSUE THREAD

**Issue by sjakthol** [HSLdevcom/digitransit-ui#782]
Currently each request to the GraphQL endpoint causes a new preflight OPTIONS request be sent to the server. Needless to say, this is problematic for performance since each request triggers two sequential requests to the API before the response is available.

Since the origin, URL and request method for the GraphQL requests are always the same (at least those I've seen), you should be able to use the Access-Control-Max-Age header to avoid unneeded preflight requests.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Max-Age

**Comment by hannesj** [comment]
Hi,

Thanks for the tip, I noticed this by myself but didn't have time to research at that moment. Fixed in https://github.com/HSLdevcom/OpenTripPlanner/commit/6c7b8a549626e87e750b9cd95fb81457f02204a2 and should be deployed this week.

**Comment by hannesj** [comment]
Deployed to production.
