### ISSUE TITLE
Page transition modifications

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#84]
Currently UI waits for server response on the page that link was clicked on. E.g. 
1) User clicks stop card on front page
2) UI fetches stop card info from server
3) UI transitions to next page
4) new page is drawn

This lag is something that we would like to get rid of. So, we should change implementation so that we will immediately move to next page and then fetch data needed for the page.

In future, we might need some kind of "loading" icon while data is being downloaded.

**Comment by hannesj** [comment]
Done in #89
