### ISSUE TITLE
Maintain UI page state between page loads

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-ui#85]
We should have some kind of "page state cache" that should be utilized as follows:

Map
1) User clicks on stop and a "stop popup" is shown
2) User clicks "next departures" and is taken to stop page
3) User clicks "back"
--> In this case:
- Map should be in same location as it was in step 2
- "stop popup" should be visible

Route summary page:
1) User activates route suggestion 2
2) User clicks on arrow to see route suggestion 2
3) User clicks back
--> In this case:
- Option 2 should be selected. Note! if user decides to swipe to option 3 and then moves back, option 3 should be highlighted.

**Comment by hannesj** [comment]
Related to #131
