### ISSUE TITLE
Custom departure time is forgotten

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#936]
If I search a route from A to B and set departure time, for example, tomorrow at 5 pm, I'll get the correct results. However, if I change the destination to C, the search will use the current time although the custom departure time is still visible.

**Comment by hannesj** [comment]
This will be fixed when https://github.com/HSLdevcom/digitransit-ui/tree/context-aware-rerouting is merged

**Comment by hannesj** [comment]
@ttsirkia This should have been fixed on https://dev.reittiopas.fi now, could you confirm.

**Comment by ttsirkia** [comment]
Yes, it works perfectly.
