### ISSUE TITLE
Time selector component uses bad colors

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#937]
The numbers in the time selector component should be gray or black. Currently they are almost invisible.

![timeselector](https://cloud.githubusercontent.com/assets/2797729/20041827/ce18c7fc-a477-11e6-914d-6af0a39e2e1f.png)

(Windows with newest FF)

**Comment by Macroz** [comment]
Same problem in Linux FF also.

**Comment by ttsirkia** [comment]
It seems that one of the `div` elements define `color: rgb(255, 255, 255)`. In the original theme of Material UI timepicker, the numbers seem to be dark gray.

**Comment by Macroz** [comment]
This will be fixed in https://digitransit.atlassian.net/browse/DT-1567.

**Comment by rrudd** [comment]
This was addressed by #938
