### ISSUE TITLE
Three destination favorites is not enough

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#993]
There should be option to add more than three destination favorites.

If the problem is that querying the results for all is too resource intensive, there could be, for example, five small squares below the big ones without immediate routing results. The query is done after clicking the small tile.

**Comment by rrudd** [comment]
We agree that users should be able to add more than three favourite locations. In fact, our latest designs suggest a sideways scrollable list of favourite tiles. Some solution to this will probably be implemented eventually, but it is unlikely that it will be done before launch.

**Comment by hannesj** [comment]
Has been implemented
